/** Nutrientes por 100 g. */
export type FoodSeed = {
  name: string;
  category: string;
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sodium: number;
};

type Base = FoodSeed;

/** Tabela ampliada (valores típicos por 100 g — referência TACO/média comercial). */
const BASE: Base[] = [
  // Cereais e farinhas
  { name: "Arroz branco cozido", category: "Cereais", kcal: 128, protein: 2.5, carbs: 28, fat: 0.2, fiber: 0.4, sodium: 1 },
  { name: "Arroz integral cozido", category: "Cereais", kcal: 124, protein: 2.6, carbs: 25.8, fat: 1, fiber: 2.7, sodium: 1 },
  { name: "Arroz parboilizado cozido", category: "Cereais", kcal: 130, protein: 2.7, carbs: 28.1, fat: 0.3, fiber: 0.8, sodium: 1 },
  { name: "Arroz negro cozido", category: "Cereais", kcal: 130, protein: 3.5, carbs: 26, fat: 1.2, fiber: 2.5, sodium: 2 },
  { name: "Aveia em flocos", category: "Cereais", kcal: 394, protein: 13.9, carbs: 66.6, fat: 8.5, fiber: 9.1, sodium: 5 },
  { name: "Farelo de aveia", category: "Cereais", kcal: 246, protein: 17, carbs: 66, fat: 7, fiber: 15, sodium: 4 },
  { name: "Pão francês", category: "Cereais", kcal: 300, protein: 8, carbs: 58.6, fat: 3.1, fiber: 2.3, sodium: 648 },
  { name: "Pão integral", category: "Cereais", kcal: 253, protein: 9.4, carbs: 42.5, fat: 3.5, fiber: 6.9, sodium: 506 },
  { name: "Pão de forma branco", category: "Cereais", kcal: 253, protein: 7.5, carbs: 48, fat: 3, fiber: 2.3, sodium: 480 },
  { name: "Pão de forma integral", category: "Cereais", kcal: 247, protein: 9, carbs: 41, fat: 4, fiber: 6, sodium: 420 },
  { name: "Pão sírio", category: "Cereais", kcal: 275, protein: 9, carbs: 55, fat: 1.2, fiber: 2.2, sodium: 536 },
  { name: "Pão de centeio", category: "Cereais", kcal: 259, protein: 8.5, carbs: 48, fat: 3.3, fiber: 5.8, sodium: 603 },
  { name: "Torrada integral", category: "Cereais", kcal: 377, protein: 11, carbs: 66, fat: 6, fiber: 6, sodium: 500 },
  { name: "Macarrão cozido", category: "Cereais", kcal: 158, protein: 5.8, carbs: 30.9, fat: 0.9, fiber: 1.8, sodium: 1 },
  { name: "Macarrão integral cozido", category: "Cereais", kcal: 124, protein: 5.3, carbs: 26, fat: 0.5, fiber: 3.5, sodium: 2 },
  { name: "Nhoque de batata", category: "Cereais", kcal: 133, protein: 3.5, carbs: 28, fat: 0.8, fiber: 1.5, sodium: 280 },
  { name: "Lasanha (massa crua)", category: "Cereais", kcal: 355, protein: 12, carbs: 72, fat: 1.5, fiber: 3, sodium: 10 },
  { name: "Tapioca (goma hidratada)", category: "Cereais", kcal: 240, protein: 0.2, carbs: 60, fat: 0, fiber: 0.5, sodium: 1 },
  { name: "Cuscuz de milho cozido", category: "Cereais", kcal: 113, protein: 2.2, carbs: 25, fat: 0.5, fiber: 2, sodium: 2 },
  { name: "Quinoa cozida", category: "Cereais", kcal: 120, protein: 4.4, carbs: 21.3, fat: 1.9, fiber: 2.8, sodium: 7 },
  { name: "Cuscuz marroquino cozido", category: "Cereais", kcal: 112, protein: 3.8, carbs: 23, fat: 0.2, fiber: 1.4, sodium: 5 },
  { name: "Milho verde cozido", category: "Cereais", kcal: 98, protein: 3.2, carbs: 21, fat: 1.2, fiber: 2.4, sodium: 1 },
  { name: "Farinha de milho", category: "Cereais", kcal: 351, protein: 7, carbs: 79, fat: 1.5, fiber: 5, sodium: 1 },
  { name: "Farinha de trigo", category: "Cereais", kcal: 364, protein: 10, carbs: 76, fat: 1, fiber: 2.3, sodium: 2 },
  { name: "Farinha de rosca", category: "Cereais", kcal: 395, protein: 13, carbs: 72, fat: 5, fiber: 4, sodium: 700 },
  { name: "Farinha de mandioca", category: "Cereais", kcal: 361, protein: 1.5, carbs: 88, fat: 0.3, fiber: 3.5, sodium: 1 },
  { name: "Fubá", category: "Cereais", kcal: 353, protein: 7.2, carbs: 78, fat: 1.5, fiber: 4.8, sodium: 1 },
  { name: "Granola", category: "Cereais", kcal: 471, protein: 10, carbs: 64, fat: 20, fiber: 7, sodium: 20 },
  { name: "Muesli", category: "Cereais", kcal: 350, protein: 9, carbs: 66, fat: 6, fiber: 7, sodium: 40 },
  { name: "Cereal matinal sem açúcar", category: "Cereais", kcal: 360, protein: 8, carbs: 80, fat: 1.5, fiber: 8, sodium: 300 },
  { name: "Biscoito cream cracker", category: "Cereais", kcal: 432, protein: 10, carbs: 70, fat: 12, fiber: 2.5, sodium: 710 },
  { name: "Biscoito integral", category: "Cereais", kcal: 420, protein: 9, carbs: 65, fat: 14, fiber: 6, sodium: 480 },
  { name: "Barra de cereal", category: "Cereais", kcal: 400, protein: 5, carbs: 70, fat: 12, fiber: 4, sodium: 150 },
  { name: "Pipoca sem óleo", category: "Cereais", kcal: 387, protein: 13, carbs: 78, fat: 4.5, fiber: 15, sodium: 8 },
  { name: "Polenta cozida", category: "Cereais", kcal: 70, protein: 1.5, carbs: 15, fat: 0.3, fiber: 1, sodium: 5 },
  { name: "Mingau de aveia", category: "Cereais", kcal: 71, protein: 2.5, carbs: 12, fat: 1.5, fiber: 1.7, sodium: 40 },

  // Tubérculos
  { name: "Batata inglesa cozida", category: "Tubérculos", kcal: 87, protein: 1.9, carbs: 20.1, fat: 0.1, fiber: 1.3, sodium: 2 },
  { name: "Batata inglesa assada", category: "Tubérculos", kcal: 93, protein: 2.1, carbs: 21, fat: 0.1, fiber: 2.2, sodium: 5 },
  { name: "Batata frita (média)", category: "Tubérculos", kcal: 267, protein: 3.5, carbs: 35, fat: 13, fiber: 3, sodium: 210 },
  { name: "Batata-doce cozida", category: "Tubérculos", kcal: 77, protein: 0.6, carbs: 18.4, fat: 0.1, fiber: 2.2, sodium: 9 },
  { name: "Batata-doce assada", category: "Tubérculos", kcal: 90, protein: 2, carbs: 20.7, fat: 0.1, fiber: 3.3, sodium: 36 },
  { name: "Mandioca cozida", category: "Tubérculos", kcal: 125, protein: 0.6, carbs: 30.1, fat: 0.3, fiber: 1.6, sodium: 1 },
  { name: "Mandioca frita", category: "Tubérculos", kcal: 300, protein: 1.5, carbs: 40, fat: 15, fiber: 2, sodium: 10 },
  { name: "Inhame cozido", category: "Tubérculos", kcal: 96, protein: 2, carbs: 23, fat: 0.1, fiber: 1.5, sodium: 2 },
  { name: "Cará cozido", category: "Tubérculos", kcal: 96, protein: 2.3, carbs: 23, fat: 0.1, fiber: 2, sodium: 3 },
  { name: "Mandioquinha cozida", category: "Tubérculos", kcal: 100, protein: 1, carbs: 24, fat: 0.2, fiber: 2.1, sodium: 4 },
  { name: "Nabo cozido", category: "Tubérculos", kcal: 22, protein: 0.7, carbs: 5, fat: 0.1, fiber: 2, sodium: 25 },
  { name: "Beterraba cozida", category: "Tubérculos", kcal: 44, protein: 1.6, carbs: 10, fat: 0.2, fiber: 2, sodium: 40 },
  { name: "Rabanete", category: "Tubérculos", kcal: 16, protein: 0.7, carbs: 3.4, fat: 0.1, fiber: 1.6, sodium: 39 },

  // Leguminosas
  { name: "Feijão carioca cozido", category: "Leguminosas", kcal: 76, protein: 4.8, carbs: 13.6, fat: 0.5, fiber: 8.5, sodium: 2 },
  { name: "Feijão preto cozido", category: "Leguminosas", kcal: 77, protein: 4.5, carbs: 14, fat: 0.5, fiber: 8.4, sodium: 2 },
  { name: "Feijão branco cozido", category: "Leguminosas", kcal: 118, protein: 8.1, carbs: 21, fat: 0.5, fiber: 6.3, sodium: 5 },
  { name: "Feijão fradinho cozido", category: "Leguminosas", kcal: 77, protein: 5.1, carbs: 13.5, fat: 0.5, fiber: 5.5, sodium: 3 },
  { name: "Feijão verde cozido", category: "Leguminosas", kcal: 31, protein: 1.8, carbs: 7, fat: 0.1, fiber: 2.7, sodium: 1 },
  { name: "Lentilha cozida", category: "Leguminosas", kcal: 93, protein: 6.3, carbs: 16.3, fat: 0.4, fiber: 7.9, sodium: 2 },
  { name: "Grão-de-bico cozido", category: "Leguminosas", kcal: 121, protein: 7.7, carbs: 19.4, fat: 2.1, fiber: 5.1, sodium: 6 },
  { name: "Ervilha cozida", category: "Leguminosas", kcal: 74, protein: 5.1, carbs: 12.4, fat: 0.4, fiber: 5.1, sodium: 3 },
  { name: "Ervilha fresca", category: "Leguminosas", kcal: 81, protein: 5.4, carbs: 14, fat: 0.4, fiber: 5.5, sodium: 5 },
  { name: "Soja cozida", category: "Leguminosas", kcal: 141, protein: 12.5, carbs: 10, fat: 6.4, fiber: 5.5, sodium: 1 },
  { name: "Edamame", category: "Leguminosas", kcal: 121, protein: 11.9, carbs: 8.9, fat: 5.2, fiber: 5.2, sodium: 6 },
  { name: "Tofu firme", category: "Leguminosas", kcal: 76, protein: 8, carbs: 1.9, fat: 4.8, fiber: 0.3, sodium: 7 },
  { name: "Tofu silk", category: "Leguminosas", kcal: 55, protein: 5.3, carbs: 2.3, fat: 2.7, fiber: 0.2, sodium: 8 },
  { name: "Proteína de soja texturizada hidratada", category: "Leguminosas", kcal: 100, protein: 15, carbs: 7, fat: 0.5, fiber: 5, sodium: 10 },
  { name: "Homus", category: "Leguminosas", kcal: 166, protein: 8, carbs: 14, fat: 9.6, fiber: 6, sodium: 379 },
  { name: "Guacamole", category: "Leguminosas", kcal: 150, protein: 2, carbs: 8, fat: 13, fiber: 6, sodium: 200 },

  // Carnes
  { name: "Peito de frango grelhado", category: "Carnes", kcal: 159, protein: 32, carbs: 0, fat: 2.5, fiber: 0, sodium: 63 },
  { name: "Peito de frango cru", category: "Carnes", kcal: 120, protein: 22, carbs: 0, fat: 2.6, fiber: 0, sodium: 45 },
  { name: "Coxa de frango assada", category: "Carnes", kcal: 215, protein: 25, carbs: 0, fat: 12, fiber: 0, sodium: 84 },
  { name: "Sobrecoxa de frango assada", category: "Carnes", kcal: 230, protein: 24, carbs: 0, fat: 14, fiber: 0, sodium: 90 },
  { name: "Frango desfiado", category: "Carnes", kcal: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, sodium: 70 },
  { name: "Carne bovina magra grelhada", category: "Carnes", kcal: 219, protein: 32, carbs: 0, fat: 9.5, fiber: 0, sodium: 58 },
  { name: "Patinho moído cozido", category: "Carnes", kcal: 219, protein: 31, carbs: 0, fat: 10, fiber: 0, sodium: 70 },
  { name: "Alcatra grelhada", category: "Carnes", kcal: 215, protein: 30, carbs: 0, fat: 10, fiber: 0, sodium: 55 },
  { name: "Coxão mole cozido", category: "Carnes", kcal: 200, protein: 29, carbs: 0, fat: 9, fiber: 0, sodium: 60 },
  { name: "Músculo bovino cozido", category: "Carnes", kcal: 194, protein: 31, carbs: 0, fat: 7, fiber: 0, sodium: 55 },
  { name: "Fígado bovino grelhado", category: "Carnes", kcal: 175, protein: 26, carbs: 4, fat: 5, fiber: 0, sodium: 80 },
  { name: "Carne de porco lombo", category: "Carnes", kcal: 180, protein: 28, carbs: 0, fat: 7, fiber: 0, sodium: 55 },
  { name: "Lombo suíno assado", category: "Carnes", kcal: 200, protein: 27, carbs: 0, fat: 10, fiber: 0, sodium: 60 },
  { name: "Bisteca suína grelhada", category: "Carnes", kcal: 250, protein: 26, carbs: 0, fat: 16, fiber: 0, sodium: 65 },
  { name: "Bacon frito", category: "Carnes", kcal: 541, protein: 37, carbs: 1.4, fat: 42, fiber: 0, sodium: 1717 },
  { name: "Linguiça calabresa", category: "Carnes", kcal: 300, protein: 16, carbs: 2, fat: 25, fiber: 0, sodium: 900 },
  { name: "Salsicha", category: "Carnes", kcal: 280, protein: 12, carbs: 3, fat: 24, fiber: 0, sodium: 950 },
  { name: "Presunto magro", category: "Carnes", kcal: 109, protein: 17, carbs: 1.5, fat: 3.5, fiber: 0, sodium: 900 },
  { name: "Peito de peru", category: "Carnes", kcal: 100, protein: 18, carbs: 1, fat: 2, fiber: 0, sodium: 850 },
  { name: "Mortadela", category: "Carnes", kcal: 269, protein: 12, carbs: 3, fat: 23, fiber: 0, sodium: 1100 },
  { name: "Carne seca dessalgada", category: "Carnes", kcal: 250, protein: 36, carbs: 0, fat: 12, fiber: 0, sodium: 1200 },
  { name: "Carne de sol", category: "Carnes", kcal: 240, protein: 35, carbs: 0, fat: 11, fiber: 0, sodium: 1500 },
  { name: "Hambúrguer bovino grelhado", category: "Carnes", kcal: 250, protein: 25, carbs: 0, fat: 17, fiber: 0, sodium: 75 },
  { name: "Peru peito assado", category: "Carnes", kcal: 135, protein: 29, carbs: 0, fat: 1.5, fiber: 0, sodium: 50 },

  // Peixes e frutos do mar
  { name: "Peixe tilápia grelhada", category: "Peixes", kcal: 96, protein: 20, carbs: 0, fat: 1.7, fiber: 0, sodium: 52 },
  { name: "Salmão grelhado", category: "Peixes", kcal: 208, protein: 22, carbs: 0, fat: 13, fiber: 0, sodium: 59 },
  { name: "Atum em água (drenado)", category: "Peixes", kcal: 116, protein: 26, carbs: 0, fat: 0.8, fiber: 0, sodium: 320 },
  { name: "Atum fresco grelhado", category: "Peixes", kcal: 144, protein: 23, carbs: 0, fat: 5, fiber: 0, sodium: 40 },
  { name: "Sardinha em óleo (drenada)", category: "Peixes", kcal: 208, protein: 25, carbs: 0, fat: 11, fiber: 0, sodium: 400 },
  { name: "Sardinha fresca grelhada", category: "Peixes", kcal: 180, protein: 22, carbs: 0, fat: 10, fiber: 0, sodium: 80 },
  { name: "Bacalhau dessalgado cozido", category: "Peixes", kcal: 110, protein: 24, carbs: 0, fat: 1, fiber: 0, sodium: 400 },
  { name: "Merluza grelhada", category: "Peixes", kcal: 90, protein: 18, carbs: 0, fat: 1.5, fiber: 0, sodium: 70 },
  { name: "Pescada branca grelhada", category: "Peixes", kcal: 95, protein: 19, carbs: 0, fat: 1.8, fiber: 0, sodium: 60 },
  { name: "Camarão cozido", category: "Peixes", kcal: 99, protein: 24, carbs: 0.2, fat: 0.3, fiber: 0, sodium: 111 },
  { name: "Lula grelhada", category: "Peixes", kcal: 92, protein: 16, carbs: 3, fat: 1.4, fiber: 0, sodium: 40 },
  { name: "Polvo cozido", category: "Peixes", kcal: 82, protein: 15, carbs: 2.2, fat: 1, fiber: 0, sodium: 230 },
  { name: "Mexilhão cozido", category: "Peixes", kcal: 86, protein: 12, carbs: 3.7, fat: 2.2, fiber: 0, sodium: 286 },
  { name: "Anchova", category: "Peixes", kcal: 131, protein: 20, carbs: 0, fat: 4.8, fiber: 0, sodium: 104 },
  { name: "Truta grelhada", category: "Peixes", kcal: 150, protein: 21, carbs: 0, fat: 7, fiber: 0, sodium: 50 },

  // Ovos
  { name: "Ovo de galinha inteiro cozido", category: "Ovos", kcal: 146, protein: 13, carbs: 0.6, fat: 9.5, fiber: 0, sodium: 146 },
  { name: "Ovo mexido", category: "Ovos", kcal: 167, protein: 11, carbs: 1.5, fat: 12, fiber: 0, sodium: 170 },
  { name: "Ovo frito", category: "Ovos", kcal: 196, protein: 13.6, carbs: 0.8, fat: 15, fiber: 0, sodium: 160 },
  { name: "Clara de ovo cozida", category: "Ovos", kcal: 59, protein: 13.5, carbs: 0.7, fat: 0.2, fiber: 0, sodium: 166 },
  { name: "Gema de ovo cozida", category: "Ovos", kcal: 353, protein: 16, carbs: 1.8, fat: 31, fiber: 0, sodium: 50 },
  { name: "Omelete simples (2 ovos)", category: "Ovos", kcal: 154, protein: 11, carbs: 0.6, fat: 12, fiber: 0, sodium: 150 },

  // Laticínios
  { name: "Leite integral", category: "Laticínios", kcal: 61, protein: 3.2, carbs: 4.8, fat: 3.2, fiber: 0, sodium: 43 },
  { name: "Leite semidesnatado", category: "Laticínios", kcal: 47, protein: 3.3, carbs: 4.9, fat: 1.5, fiber: 0, sodium: 44 },
  { name: "Leite desnatado", category: "Laticínios", kcal: 35, protein: 3.4, carbs: 5, fat: 0.2, fiber: 0, sodium: 44 },
  { name: "Leite em pó integral", category: "Laticínios", kcal: 496, protein: 26, carbs: 38, fat: 27, fiber: 0, sodium: 370 },
  { name: "Iogurte natural integral", category: "Laticínios", kcal: 61, protein: 3.5, carbs: 4.7, fat: 3.3, fiber: 0, sodium: 46 },
  { name: "Iogurte natural desnatado", category: "Laticínios", kcal: 41, protein: 4.3, carbs: 5.5, fat: 0.2, fiber: 0, sodium: 50 },
  { name: "Iogurte grego natural", category: "Laticínios", kcal: 97, protein: 9, carbs: 3.6, fat: 5, fiber: 0, sodium: 36 },
  { name: "Iogurte grego zero", category: "Laticínios", kcal: 57, protein: 10, carbs: 4, fat: 0.2, fiber: 0, sodium: 40 },
  { name: "Queijo minas frescal", category: "Laticínios", kcal: 264, protein: 17.4, carbs: 3.2, fat: 20.5, fiber: 0, sodium: 31 },
  { name: "Queijo cottage", category: "Laticínios", kcal: 98, protein: 11, carbs: 3.4, fat: 4.3, fiber: 0, sodium: 364 },
  { name: "Queijo mussarela", category: "Laticínios", kcal: 280, protein: 22, carbs: 2.2, fat: 20, fiber: 0, sodium: 550 },
  { name: "Queijo prato", category: "Laticínios", kcal: 360, protein: 25, carbs: 1.5, fat: 28, fiber: 0, sodium: 700 },
  { name: "Queijo parmesão", category: "Laticínios", kcal: 420, protein: 36, carbs: 3.5, fat: 29, fiber: 0, sodium: 1529 },
  { name: "Queijo cheddar", category: "Laticínios", kcal: 403, protein: 25, carbs: 1.3, fat: 33, fiber: 0, sodium: 621 },
  { name: "Queijo ricota", category: "Laticínios", kcal: 140, protein: 11, carbs: 3, fat: 10, fiber: 0, sodium: 90 },
  { name: "Queijo cottage light", category: "Laticínios", kcal: 72, protein: 12, carbs: 3.5, fat: 1, fiber: 0, sodium: 350 },
  { name: "Requeijão cremoso", category: "Laticínios", kcal: 257, protein: 8, carbs: 3, fat: 24, fiber: 0, sodium: 450 },
  { name: "Requeijão light", category: "Laticínios", kcal: 140, protein: 8, carbs: 4, fat: 10, fiber: 0, sodium: 400 },
  { name: "Cream cheese", category: "Laticínios", kcal: 342, protein: 6, carbs: 4, fat: 34, fiber: 0, sodium: 321 },
  { name: "Creme de leite", category: "Laticínios", kcal: 195, protein: 2.5, carbs: 3.5, fat: 20, fiber: 0, sodium: 40 },
  { name: "Manteiga com sal", category: "Laticínios", kcal: 717, protein: 0.9, carbs: 0.1, fat: 81, fiber: 0, sodium: 576 },
  { name: "Coalhada", category: "Laticínios", kcal: 60, protein: 4, carbs: 5, fat: 2.5, fiber: 0, sodium: 50 },
  { name: "Kefir de leite", category: "Laticínios", kcal: 55, protein: 3.5, carbs: 4.5, fat: 2.5, fiber: 0, sodium: 40 },

  // Frutas
  { name: "Banana prata", category: "Frutas", kcal: 98, protein: 1.3, carbs: 26, fat: 0.1, fiber: 2, sodium: 0 },
  { name: "Banana nanica", category: "Frutas", kcal: 92, protein: 1.3, carbs: 23.8, fat: 0.1, fiber: 2.6, sodium: 0 },
  { name: "Banana da terra", category: "Frutas", kcal: 128, protein: 1.4, carbs: 33.7, fat: 0.2, fiber: 2.3, sodium: 0 },
  { name: "Maçã com casca", category: "Frutas", kcal: 56, protein: 0.3, carbs: 15, fat: 0.2, fiber: 1.3, sodium: 0 },
  { name: "Pêra", category: "Frutas", kcal: 53, protein: 0.4, carbs: 14, fat: 0.1, fiber: 3, sodium: 1 },
  { name: "Mamão papaia", category: "Frutas", kcal: 40, protein: 0.5, carbs: 10.4, fat: 0.1, fiber: 1, sodium: 3 },
  { name: "Mamão formosa", category: "Frutas", kcal: 45, protein: 0.8, carbs: 11.6, fat: 0.1, fiber: 1.8, sodium: 3 },
  { name: "Laranja pera", category: "Frutas", kcal: 37, protein: 0.8, carbs: 8.9, fat: 0.1, fiber: 0.8, sodium: 0 },
  { name: "Laranja bahia", category: "Frutas", kcal: 45, protein: 1, carbs: 11, fat: 0.1, fiber: 1.5, sodium: 0 },
  { name: "Tangerina", category: "Frutas", kcal: 38, protein: 0.8, carbs: 9.3, fat: 0.1, fiber: 1.2, sodium: 0 },
  { name: "Limão", category: "Frutas", kcal: 29, protein: 1.1, carbs: 9.3, fat: 0.3, fiber: 2.8, sodium: 2 },
  { name: "Morango", category: "Frutas", kcal: 30, protein: 0.9, carbs: 6.8, fat: 0.3, fiber: 1.7, sodium: 1 },
  { name: "Uva itália", category: "Frutas", kcal: 53, protein: 0.7, carbs: 13, fat: 0.2, fiber: 0.9, sodium: 0 },
  { name: "Uva rubi", category: "Frutas", kcal: 49, protein: 0.6, carbs: 12, fat: 0.2, fiber: 0.9, sodium: 0 },
  { name: "Abacate", category: "Frutas", kcal: 96, protein: 1.2, carbs: 6, fat: 8.4, fiber: 6.3, sodium: 0 },
  { name: "Manga tommy", category: "Frutas", kcal: 64, protein: 0.5, carbs: 16.5, fat: 0.3, fiber: 1.6, sodium: 0 },
  { name: "Manga palmer", category: "Frutas", kcal: 60, protein: 0.5, carbs: 15, fat: 0.3, fiber: 1.6, sodium: 0 },
  { name: "Melancia", category: "Frutas", kcal: 33, protein: 0.9, carbs: 8.1, fat: 0, fiber: 0.1, sodium: 0 },
  { name: "Melão", category: "Frutas", kcal: 29, protein: 0.7, carbs: 7, fat: 0.1, fiber: 0.6, sodium: 10 },
  { name: "Abacaxi", category: "Frutas", kcal: 48, protein: 0.9, carbs: 12.3, fat: 0.1, fiber: 1, sodium: 1 },
  { name: "Kiwi", category: "Frutas", kcal: 51, protein: 1, carbs: 12, fat: 0.4, fiber: 2.7, sodium: 3 },
  { name: "Goiaba", category: "Frutas", kcal: 54, protein: 1.1, carbs: 13, fat: 0.5, fiber: 6.3, sodium: 2 },
  { name: "Caqui", category: "Frutas", kcal: 71, protein: 0.4, carbs: 19, fat: 0.1, fiber: 3.6, sodium: 1 },
  { name: "Figo", category: "Frutas", kcal: 74, protein: 0.8, carbs: 19, fat: 0.3, fiber: 2.9, sodium: 1 },
  { name: "Ameixa", category: "Frutas", kcal: 46, protein: 0.7, carbs: 11.4, fat: 0.3, fiber: 1.4, sodium: 0 },
  { name: "Pêssego", category: "Frutas", kcal: 36, protein: 0.8, carbs: 9, fat: 0.1, fiber: 1.5, sodium: 0 },
  { name: "Cereja", category: "Frutas", kcal: 50, protein: 1, carbs: 12, fat: 0.3, fiber: 1.6, sodium: 0 },
  { name: "Framboesa", category: "Frutas", kcal: 52, protein: 1.2, carbs: 12, fat: 0.7, fiber: 6.5, sodium: 1 },
  { name: "Mirtilo", category: "Frutas", kcal: 57, protein: 0.7, carbs: 14.5, fat: 0.3, fiber: 2.4, sodium: 1 },
  { name: "Maracujá", category: "Frutas", kcal: 68, protein: 2, carbs: 16, fat: 0.7, fiber: 10, sodium: 14 },
  { name: "Acerola", category: "Frutas", kcal: 33, protein: 0.9, carbs: 8, fat: 0.2, fiber: 1.5, sodium: 2 },
  { name: "Caju", category: "Frutas", kcal: 43, protein: 1, carbs: 10, fat: 0.3, fiber: 1.7, sodium: 3 },
  { name: "Jabuticaba", category: "Frutas", kcal: 58, protein: 0.6, carbs: 15, fat: 0.1, fiber: 2.3, sodium: 0 },
  { name: "Coco fresco", category: "Frutas", kcal: 354, protein: 3.3, carbs: 15, fat: 33, fiber: 9, sodium: 20 },
  { name: "Açaí polpa sem xarope", category: "Frutas", kcal: 58, protein: 0.8, carbs: 6.2, fat: 3.9, fiber: 2.6, sodium: 5 },
  { name: "Cupuaçu polpa", category: "Frutas", kcal: 49, protein: 1.2, carbs: 11, fat: 0.8, fiber: 2, sodium: 2 },
  { name: "Uva-passa", category: "Frutas", kcal: 299, protein: 3.1, carbs: 79, fat: 0.5, fiber: 3.7, sodium: 11 },
  { name: "Damasco seco", category: "Frutas", kcal: 241, protein: 3.4, carbs: 63, fat: 0.5, fiber: 7.3, sodium: 10 },
  { name: "Tâmara", category: "Frutas", kcal: 282, protein: 2.5, carbs: 75, fat: 0.4, fiber: 8, sodium: 2 },

  // Verduras e legumes
  { name: "Alface crespa", category: "Verduras", kcal: 11, protein: 1.3, carbs: 1.7, fat: 0.2, fiber: 1.8, sodium: 7 },
  { name: "Alface americana", category: "Verduras", kcal: 14, protein: 0.9, carbs: 3, fat: 0.1, fiber: 1.3, sodium: 8 },
  { name: "Rúcula", category: "Verduras", kcal: 25, protein: 2.6, carbs: 3.7, fat: 0.7, fiber: 1.6, sodium: 27 },
  { name: "Agrião", category: "Verduras", kcal: 17, protein: 2.3, carbs: 1.3, fat: 0.2, fiber: 1.5, sodium: 30 },
  { name: "Espinafre cru", category: "Verduras", kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, sodium: 79 },
  { name: "Espinafre cozido", category: "Verduras", kcal: 16, protein: 2, carbs: 2.1, fat: 0.2, fiber: 1.8, sodium: 18 },
  { name: "Couve crua", category: "Verduras", kcal: 27, protein: 2.9, carbs: 4.3, fat: 0.5, fiber: 3.1, sodium: 25 },
  { name: "Couve refogada", category: "Verduras", kcal: 90, protein: 1.7, carbs: 8.7, fat: 6.1, fiber: 3.5, sodium: 8 },
  { name: "Brócolis cru", category: "Verduras", kcal: 25, protein: 3, carbs: 4, fat: 0.3, fiber: 2.5, sodium: 27 },
  { name: "Brócolis cozido", category: "Verduras", kcal: 25, protein: 2.1, carbs: 4.4, fat: 0.5, fiber: 3.4, sodium: 6 },
  { name: "Couve-flor cozida", category: "Verduras", kcal: 23, protein: 1.8, carbs: 4.5, fat: 0.3, fiber: 2.1, sodium: 8 },
  { name: "Repolho cru", category: "Verduras", kcal: 17, protein: 1.3, carbs: 3.9, fat: 0.1, fiber: 1.9, sodium: 12 },
  { name: "Repolho roxo", category: "Verduras", kcal: 31, protein: 1.4, carbs: 7.4, fat: 0.2, fiber: 2.1, sodium: 27 },
  { name: "Tomate", category: "Verduras", kcal: 15, protein: 1.1, carbs: 3.1, fat: 0.2, fiber: 1.2, sodium: 3 },
  { name: "Tomate cereja", category: "Verduras", kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2, sodium: 5 },
  { name: "Cenoura crua", category: "Verduras", kcal: 34, protein: 0.9, carbs: 7.7, fat: 0.2, fiber: 3.2, sodium: 35 },
  { name: "Cenoura cozida", category: "Verduras", kcal: 30, protein: 0.8, carbs: 7, fat: 0.2, fiber: 2.8, sodium: 40 },
  { name: "Abobrinha cozida", category: "Verduras", kcal: 15, protein: 1.1, carbs: 3, fat: 0.2, fiber: 1.2, sodium: 1 },
  { name: "Abóbora cozida", category: "Verduras", kcal: 26, protein: 0.7, carbs: 6.5, fat: 0.1, fiber: 1.5, sodium: 1 },
  { name: "Chuchu cozido", category: "Verduras", kcal: 19, protein: 0.6, carbs: 4.5, fat: 0.1, fiber: 1.3, sodium: 2 },
  { name: "Berinjela cozida", category: "Verduras", kcal: 19, protein: 0.8, carbs: 4.4, fat: 0.2, fiber: 2.5, sodium: 1 },
  { name: "Pepino", category: "Verduras", kcal: 10, protein: 0.6, carbs: 1.8, fat: 0, fiber: 0.6, sodium: 1 },
  { name: "Pimentão vermelho", category: "Verduras", kcal: 26, protein: 1, carbs: 6, fat: 0.3, fiber: 2.1, sodium: 2 },
  { name: "Pimentão verde", category: "Verduras", kcal: 20, protein: 0.9, carbs: 4.6, fat: 0.2, fiber: 1.7, sodium: 3 },
  { name: "Cebola crua", category: "Verduras", kcal: 39, protein: 1.1, carbs: 9, fat: 0.1, fiber: 1.7, sodium: 4 },
  { name: "Alho", category: "Verduras", kcal: 113, protein: 6, carbs: 23, fat: 0.4, fiber: 2.1, sodium: 17 },
  { name: "Vagem cozida", category: "Verduras", kcal: 31, protein: 1.8, carbs: 7, fat: 0.1, fiber: 2.7, sodium: 1 },
  { name: "Quiabo cozido", category: "Verduras", kcal: 27, protein: 1.9, carbs: 5.5, fat: 0.2, fiber: 2.5, sodium: 4 },
  { name: "Jiló cozido", category: "Verduras", kcal: 27, protein: 1.4, carbs: 6, fat: 0.2, fiber: 3, sodium: 1 },
  { name: "Maxixe", category: "Verduras", kcal: 14, protein: 0.8, carbs: 2.8, fat: 0.1, fiber: 1.5, sodium: 2 },
  { name: "Palmito em conserva", category: "Verduras", kcal: 26, protein: 2.5, carbs: 4, fat: 0.3, fiber: 2, sodium: 400 },
  { name: "Cogumelo paris", category: "Verduras", kcal: 22, protein: 3.1, carbs: 3.3, fat: 0.3, fiber: 1, sodium: 5 },
  { name: "Shimeji", category: "Verduras", kcal: 34, protein: 2.5, carbs: 6, fat: 0.4, fiber: 2.5, sodium: 4 },
  { name: "Aspargo cozido", category: "Verduras", kcal: 22, protein: 2.4, carbs: 4.1, fat: 0.2, fiber: 2.1, sodium: 14 },
  { name: "Aipo (salsão)", category: "Verduras", kcal: 14, protein: 0.7, carbs: 3, fat: 0.2, fiber: 1.6, sodium: 80 },
  { name: "Milho em conserva", category: "Verduras", kcal: 80, protein: 2.5, carbs: 18, fat: 0.8, fiber: 2, sodium: 250 },
  { name: "Azeitona verde", category: "Verduras", kcal: 116, protein: 0.8, carbs: 3, fat: 11, fiber: 2.5, sodium: 1556 },
  { name: "Azeitona preta", category: "Verduras", kcal: 115, protein: 0.8, carbs: 6, fat: 10.7, fiber: 1.6, sodium: 735 },

  // Gorduras e óleos
  { name: "Azeite de oliva", category: "Gorduras", kcal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, sodium: 0 },
  { name: "Óleo de soja", category: "Gorduras", kcal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, sodium: 0 },
  { name: "Óleo de coco", category: "Gorduras", kcal: 862, protein: 0, carbs: 0, fat: 100, fiber: 0, sodium: 0 },
  { name: "Óleo de canola", category: "Gorduras", kcal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, sodium: 0 },
  { name: "Manteiga sem sal", category: "Gorduras", kcal: 726, protein: 0.4, carbs: 0, fat: 82, fiber: 0, sodium: 4 },
  { name: "Margarina", category: "Gorduras", kcal: 596, protein: 0.2, carbs: 0.5, fat: 67, fiber: 0, sodium: 700 },
  { name: "Maionese", category: "Gorduras", kcal: 680, protein: 1, carbs: 2, fat: 75, fiber: 0, sodium: 600 },
  { name: "Maionese light", category: "Gorduras", kcal: 270, protein: 0.5, carbs: 10, fat: 25, fiber: 0, sodium: 700 },
  { name: "Banha", category: "Gorduras", kcal: 902, protein: 0, carbs: 0, fat: 100, fiber: 0, sodium: 0 },

  // Oleaginosas e sementes
  { name: "Castanha-do-pará", category: "Oleaginosas", kcal: 643, protein: 14.5, carbs: 15.1, fat: 63.5, fiber: 7.9, sodium: 2 },
  { name: "Amendoim torrado", category: "Oleaginosas", kcal: 544, protein: 22.5, carbs: 20, fat: 43.9, fiber: 8, sodium: 5 },
  { name: "Pasta de amendoim", category: "Oleaginosas", kcal: 588, protein: 25, carbs: 20, fat: 50, fiber: 6, sodium: 17 },
  { name: "Castanha de caju", category: "Oleaginosas", kcal: 570, protein: 18.5, carbs: 29.1, fat: 46.3, fiber: 3.7, sodium: 4 },
  { name: "Amêndoa", category: "Oleaginosas", kcal: 581, protein: 21.2, carbs: 21.6, fat: 50, fiber: 11.8, sodium: 1 },
  { name: "Noz", category: "Oleaginosas", kcal: 654, protein: 15, carbs: 14, fat: 65, fiber: 6.7, sodium: 2 },
  { name: "Pistache", category: "Oleaginosas", kcal: 562, protein: 20, carbs: 28, fat: 45, fiber: 10, sodium: 1 },
  { name: "Avelã", category: "Oleaginosas", kcal: 628, protein: 15, carbs: 17, fat: 61, fiber: 9.7, sodium: 0 },
  { name: "Semente de girassol", category: "Oleaginosas", kcal: 584, protein: 21, carbs: 20, fat: 51, fiber: 8.6, sodium: 9 },
  { name: "Semente de abóbora", category: "Oleaginosas", kcal: 559, protein: 30, carbs: 11, fat: 49, fiber: 6, sodium: 7 },
  { name: "Linhaça farinha", category: "Oleaginosas", kcal: 495, protein: 14, carbs: 43, fat: 32, fiber: 33, sodium: 30 },
  { name: "Linhaça semente", category: "Oleaginosas", kcal: 534, protein: 18, carbs: 29, fat: 42, fiber: 27, sodium: 30 },
  { name: "Chia", category: "Oleaginosas", kcal: 486, protein: 17, carbs: 42, fat: 31, fiber: 34, sodium: 16 },
  { name: "Gergelim", category: "Oleaginosas", kcal: 573, protein: 17, carbs: 23, fat: 50, fiber: 12, sodium: 11 },
  { name: "Tahine", category: "Oleaginosas", kcal: 595, protein: 17, carbs: 21, fat: 54, fiber: 9, sodium: 45 },

  // Açúcares e doces
  { name: "Açúcar cristal", category: "Açúcares", kcal: 387, protein: 0, carbs: 99.5, fat: 0, fiber: 0, sodium: 0 },
  { name: "Açúcar mascavo", category: "Açúcares", kcal: 376, protein: 0.1, carbs: 97, fat: 0, fiber: 0, sodium: 28 },
  { name: "Açúcar demerara", category: "Açúcares", kcal: 380, protein: 0, carbs: 98, fat: 0, fiber: 0, sodium: 5 },
  { name: "Mel", category: "Açúcares", kcal: 309, protein: 0.3, carbs: 84, fat: 0, fiber: 0.2, sodium: 6 },
  { name: "Melado", category: "Açúcares", kcal: 290, protein: 0.2, carbs: 75, fat: 0.1, fiber: 0, sodium: 40 },
  { name: "Rapadura", category: "Açúcares", kcal: 380, protein: 0.5, carbs: 95, fat: 0.1, fiber: 0, sodium: 10 },
  { name: "Chocolate 70%", category: "Doces", kcal: 598, protein: 7.8, carbs: 45, fat: 42, fiber: 10, sodium: 20 },
  { name: "Chocolate ao leite", category: "Doces", kcal: 535, protein: 7.5, carbs: 59, fat: 30, fiber: 2, sodium: 80 },
  { name: "Chocolate branco", category: "Doces", kcal: 539, protein: 6, carbs: 59, fat: 32, fiber: 0.2, sodium: 90 },
  { name: "Achocolatado em pó", category: "Doces", kcal: 398, protein: 4, carbs: 85, fat: 3, fiber: 3, sodium: 100 },
  { name: "Cacau em pó 100%", category: "Doces", kcal: 228, protein: 20, carbs: 58, fat: 14, fiber: 33, sodium: 21 },
  { name: "Geleia de fruta", category: "Doces", kcal: 250, protein: 0.4, carbs: 65, fat: 0.1, fiber: 1, sodium: 30 },
  { name: "Doce de leite", category: "Doces", kcal: 315, protein: 6.5, carbs: 55, fat: 8, fiber: 0, sodium: 120 },
  { name: "Sorvete de creme", category: "Doces", kcal: 207, protein: 3.5, carbs: 24, fat: 11, fiber: 0.5, sodium: 80 },
  { name: "Pudim de leite", category: "Doces", kcal: 160, protein: 5, carbs: 28, fat: 3.5, fiber: 0, sodium: 70 },
  { name: "Brigadeiro", category: "Doces", kcal: 380, protein: 5, carbs: 55, fat: 15, fiber: 1, sodium: 60 },

  // Bebidas
  { name: "Café preto sem açúcar", category: "Bebidas", kcal: 2, protein: 0.1, carbs: 0, fat: 0, fiber: 0, sodium: 2 },
  { name: "Chá mate sem açúcar", category: "Bebidas", kcal: 2, protein: 0, carbs: 0.4, fat: 0, fiber: 0, sodium: 1 },
  { name: "Chá verde sem açúcar", category: "Bebidas", kcal: 1, protein: 0, carbs: 0.2, fat: 0, fiber: 0, sodium: 1 },
  { name: "Suco de laranja natural", category: "Bebidas", kcal: 45, protein: 0.7, carbs: 10.4, fat: 0.2, fiber: 0.2, sodium: 1 },
  { name: "Suco de uva integral", category: "Bebidas", kcal: 58, protein: 0.4, carbs: 14, fat: 0.1, fiber: 0.2, sodium: 2 },
  { name: "Suco de maracujá", category: "Bebidas", kcal: 42, protein: 0.5, carbs: 10, fat: 0.1, fiber: 0.2, sodium: 5 },
  { name: "Água de coco", category: "Bebidas", kcal: 22, protein: 0.2, carbs: 5.3, fat: 0, fiber: 0, sodium: 105 },
  { name: "Leite de amêndoas", category: "Bebidas", kcal: 24, protein: 0.5, carbs: 1, fat: 2, fiber: 0.3, sodium: 60 },
  { name: "Leite de soja", category: "Bebidas", kcal: 45, protein: 3.3, carbs: 3.5, fat: 2, fiber: 0.5, sodium: 50 },
  { name: "Leite de aveia", category: "Bebidas", kcal: 45, protein: 1, carbs: 7, fat: 1.5, fiber: 0.8, sodium: 50 },
  { name: "Refrigerante cola", category: "Bebidas", kcal: 42, protein: 0, carbs: 10.6, fat: 0, fiber: 0, sodium: 4 },
  { name: "Refrigerante zero", category: "Bebidas", kcal: 1, protein: 0, carbs: 0, fat: 0, fiber: 0, sodium: 10 },
  { name: "Cerveja pilsen", category: "Bebidas", kcal: 43, protein: 0.5, carbs: 3.6, fat: 0, fiber: 0, sodium: 4 },
  { name: "Vinho tinto", category: "Bebidas", kcal: 85, protein: 0.1, carbs: 2.6, fat: 0, fiber: 0, sodium: 5 },
  { name: "Isotônico", category: "Bebidas", kcal: 24, protein: 0, carbs: 6, fat: 0, fiber: 0, sodium: 45 },
  { name: "Água com gás", category: "Bebidas", kcal: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, sodium: 10 },

  // Suplementos e prontos
  { name: "Whey protein concentrado", category: "Suplementos", kcal: 400, protein: 80, carbs: 8, fat: 5, fiber: 0, sodium: 200 },
  { name: "Whey protein isolado", category: "Suplementos", kcal: 370, protein: 90, carbs: 2, fat: 1, fiber: 0, sodium: 150 },
  { name: "Caseína", category: "Suplementos", kcal: 370, protein: 80, carbs: 5, fat: 1.5, fiber: 0, sodium: 180 },
  { name: "Albumina em pó", category: "Suplementos", kcal: 370, protein: 82, carbs: 7, fat: 0.5, fiber: 0, sodium: 500 },
  { name: "Creatina monoidratada", category: "Suplementos", kcal: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, sodium: 0 },
  { name: "Maltodextrina", category: "Suplementos", kcal: 380, protein: 0, carbs: 95, fat: 0, fiber: 0, sodium: 20 },
  { name: "BCAA em pó", category: "Suplementos", kcal: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, sodium: 0 },
  { name: "Colágeno hidrolisado", category: "Suplementos", kcal: 360, protein: 90, carbs: 0, fat: 0, fiber: 0, sodium: 200 },
  { name: "Hipercalórico", category: "Suplementos", kcal: 400, protein: 20, carbs: 70, fat: 5, fiber: 2, sodium: 150 },

  // Pratos e preparados comuns
  { name: "Feijoada (porção média)", category: "Pratos", kcal: 170, protein: 10, carbs: 12, fat: 9, fiber: 4, sodium: 450 },
  { name: "Arroz e feijão (mistura)", category: "Pratos", kcal: 110, protein: 3.5, carbs: 20, fat: 1.5, fiber: 3, sodium: 5 },
  { name: "Salada de folhas", category: "Pratos", kcal: 20, protein: 1.5, carbs: 3, fat: 0.3, fiber: 1.5, sodium: 15 },
  { name: "Salada completa", category: "Pratos", kcal: 45, protein: 2, carbs: 6, fat: 1.5, fiber: 2.5, sodium: 40 },
  { name: "Sopa de legumes", category: "Pratos", kcal: 40, protein: 1.5, carbs: 7, fat: 0.8, fiber: 1.5, sodium: 300 },
  { name: "Caldo de feijão", category: "Pratos", kcal: 55, protein: 3, carbs: 8, fat: 1, fiber: 3, sodium: 250 },
  { name: "Vitamina de banana com leite", category: "Pratos", kcal: 80, protein: 3, carbs: 12, fat: 2, fiber: 0.8, sodium: 40 },
  { name: "Panqueca de aveia", category: "Pratos", kcal: 180, protein: 8, carbs: 22, fat: 6, fiber: 3, sodium: 200 },
  { name: "Omelete com legumes", category: "Pratos", kcal: 120, protein: 9, carbs: 4, fat: 7, fiber: 1.5, sodium: 160 },
  { name: "Strogonoff de frango", category: "Pratos", kcal: 160, protein: 12, carbs: 6, fat: 10, fiber: 0.5, sodium: 400 },
  { name: "Escondidinho de frango", category: "Pratos", kcal: 150, protein: 10, carbs: 14, fat: 6, fiber: 1.5, sodium: 350 },
  { name: "Yakisoba", category: "Pratos", kcal: 130, protein: 6, carbs: 18, fat: 4, fiber: 2, sodium: 500 },
  { name: "Sushi (média)", category: "Pratos", kcal: 140, protein: 6, carbs: 25, fat: 2, fiber: 1, sodium: 350 },
  { name: "Pizza mussarela (fatia média)", category: "Pratos", kcal: 266, protein: 11, carbs: 33, fat: 10, fiber: 2, sodium: 550 },
  { name: "Hambúrguer artesanal completo", category: "Pratos", kcal: 250, protein: 14, carbs: 20, fat: 13, fiber: 1.5, sodium: 450 },
  { name: "Pastel assado", category: "Pratos", kcal: 280, protein: 8, carbs: 30, fat: 14, fiber: 1.5, sodium: 400 },
  { name: "Coxinha assada", category: "Pratos", kcal: 220, protein: 10, carbs: 25, fat: 9, fiber: 1.5, sodium: 380 },
  { name: "Pão de queijo", category: "Pratos", kcal: 300, protein: 8, carbs: 35, fat: 14, fiber: 0.5, sodium: 450 },
  { name: "Açaí na tigela com granola", category: "Pratos", kcal: 150, protein: 3, carbs: 25, fat: 5, fiber: 3, sodium: 20 },
  { name: "Wrap de frango", category: "Pratos", kcal: 180, protein: 14, carbs: 18, fat: 6, fiber: 2, sodium: 400 },
  { name: "Sanduíche natural", category: "Pratos", kcal: 160, protein: 10, carbs: 18, fat: 5, fiber: 2, sodium: 350 },

  // Condimentos
  { name: "Sal de cozinha", category: "Condimentos", kcal: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, sodium: 38758 },
  { name: "Shoyu", category: "Condimentos", kcal: 53, protein: 5, carbs: 5, fat: 0, fiber: 0.5, sodium: 5493 },
  { name: "Shoyu light", category: "Condimentos", kcal: 40, protein: 4, carbs: 4, fat: 0, fiber: 0.4, sodium: 3000 },
  { name: "Ketchup", category: "Condimentos", kcal: 112, protein: 1.2, carbs: 26, fat: 0.2, fiber: 0.3, sodium: 907 },
  { name: "Mostarda", category: "Condimentos", kcal: 66, protein: 4, carbs: 5, fat: 3.5, fiber: 3, sodium: 1135 },
  { name: "Molho de tomate", category: "Condimentos", kcal: 30, protein: 1.2, carbs: 6, fat: 0.3, fiber: 1.5, sodium: 350 },
  { name: "Molho pesto", category: "Condimentos", kcal: 360, protein: 5, carbs: 6, fat: 36, fiber: 2, sodium: 600 },
  { name: "Vinagre", category: "Condimentos", kcal: 18, protein: 0, carbs: 0.5, fat: 0, fiber: 0, sodium: 2 },
  { name: "Limão (suco)", category: "Condimentos", kcal: 22, protein: 0.4, carbs: 6.9, fat: 0.2, fiber: 0.3, sodium: 1 },
];

/** Retorna a tabela completa sem duplicar nomes. */
export function buildFoodSeed(): FoodSeed[] {
  const seen = new Set<string>();
  const out: FoodSeed[] = [];
  for (const f of BASE) {
    const key = f.name.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(f);
  }
  return out;
}
