import type { Recipe } from "./db";

type SeedRecipe = Omit<
  Recipe,
  "id" | "userId" | "createdAt" | "updatedAt" | "isSeed"
>;

const RECIPES: SeedRecipe[] = [
  // —— Café da manhã ——
  {
    name: "Omelete de claras com espinafre",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 10,
    kcal: 180,
    protein: 22,
    carbs: 4,
    fat: 8,
    ingredients: ["4 claras", "1 ovo inteiro", "1 xíc. espinafre", "1 c.chá azeite", "Sal e pimenta"],
    steps: "Refogue o espinafre. Bata os ovos, tempere e cozinhe até firmar.",
  },
  {
    name: "Tapioca com queijo cottage e tomate",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 8,
    kcal: 260,
    protein: 16,
    carbs: 32,
    fat: 7,
    ingredients: ["40 g goma de tapioca", "80 g cottage", "Tomate fatiado", "Orégano"],
    steps: "Hidrate a tapioca na frigideira, recheie com cottage e tomate.",
  },
  {
    name: "Panqueca de banana e aveia",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 12,
    kcal: 290,
    protein: 12,
    carbs: 42,
    fat: 8,
    ingredients: ["1 banana", "2 ovos", "30 g aveia", "Canela", "1 c.chá azeite"],
    steps: "Bata tudo, frite em discos pequenos e sirva com canela.",
  },
  {
    name: "Mingau de aveia proteico",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 8,
    kcal: 340,
    protein: 28,
    carbs: 40,
    fat: 7,
    ingredients: ["40 g aveia", "200 ml leite desnatado", "1 scoop whey ou 2 claras", "Canela"],
    steps: "Cozinhe a aveia no leite, acrescente a proteína e canela.",
  },
  {
    name: "Pão integral com ovo mexido e abacate",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 10,
    kcal: 380,
    protein: 18,
    carbs: 30,
    fat: 20,
    ingredients: ["2 fatias pão integral", "2 ovos", "1/4 abacate", "Sal e limão"],
    steps: "Torre o pão, mexa os ovos e cubra com abacate amassado.",
  },
  {
    name: "Cuscuz nordestino com ovo e queijo",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 15,
    kcal: 350,
    protein: 18,
    carbs: 38,
    fat: 12,
    ingredients: ["80 g flocão de milho", "1 ovo", "30 g queijo minas", "Sal"],
    steps: "Hidrate e cozinhe o cuscuz no vapor. Sirva com ovo e queijo.",
  },
  {
    name: "Smoothie verde detox",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 5,
    kcal: 210,
    protein: 8,
    carbs: 32,
    fat: 6,
    ingredients: ["1 banana", "1 punhado espinafre", "200 ml água de coco", "1 c.sopa linhaça"],
    steps: "Bata tudo no liquidificador até ficar homogêneo.",
  },
  {
    name: "Crepioca recheada com frango",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 12,
    kcal: 310,
    protein: 28,
    carbs: 22,
    fat: 12,
    ingredients: ["2 ovos", "2 c.sopa tapioca", "80 g frango desfiado", "Temperos"],
    steps: "Misture ovo e tapioca, asse na frigideira e recheie com frango.",
  },
  {
    name: "Overnight oats com frutas vermelhas",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 5,
    kcal: 320,
    protein: 16,
    carbs: 45,
    fat: 8,
    ingredients: ["40 g aveia", "150 g iogurte natural", "Frutas vermelhas", "1 c.chá mel"],
    steps: "Misture, leve à geladeira por 6–8 h e sirva frio.",
  },
  {
    name: "Wrap integral de peito de peru",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 8,
    kcal: 300,
    protein: 22,
    carbs: 28,
    fat: 10,
    ingredients: ["1 tortilha integral", "60 g peito de peru", "Folhas", "1 c.sopa requeijão light"],
    steps: "Espalhe o requeijão, monte o wrap e enrole.",
  },

  // —— Lanches ——
  {
    name: "Iogurte com aveia e fruta",
    category: "Lanche",
    servings: 1,
    prepMinutes: 5,
    kcal: 280,
    protein: 18,
    carbs: 35,
    fat: 7,
    ingredients: ["170 g iogurte grego", "30 g aveia", "1 banana ou morango", "Canela"],
    steps: "Misture iogurte e aveia; cubra com fruta e canela.",
  },
  {
    name: "Vitamina proteica pós-treino",
    category: "Lanche",
    servings: 1,
    prepMinutes: 5,
    kcal: 320,
    protein: 30,
    carbs: 38,
    fat: 6,
    ingredients: ["1 scoop whey", "1 banana", "200 ml leite desnatado", "Aveia opcional"],
    steps: "Bata no liquidificador até homogenizar.",
  },
  {
    name: "Mix de castanhas (porção controlada)",
    category: "Lanche",
    servings: 1,
    prepMinutes: 1,
    kcal: 180,
    protein: 5,
    carbs: 6,
    fat: 16,
    ingredients: ["20 g castanha-do-pará / caju / amêndoa"],
    steps: "Consuma a porção medida; não coma direto do pacote.",
  },
  {
    name: "Maçã com pasta de amendoim",
    category: "Lanche",
    servings: 1,
    prepMinutes: 3,
    kcal: 220,
    protein: 6,
    carbs: 24,
    fat: 12,
    ingredients: ["1 maçã", "1 c.sopa pasta de amendoim integral"],
    steps: "Corte a maçã e sirva com a pasta.",
  },
  {
    name: "Queijo cottage com abacaxi",
    category: "Lanche",
    servings: 1,
    prepMinutes: 3,
    kcal: 160,
    protein: 18,
    carbs: 12,
    fat: 4,
    ingredients: ["150 g cottage", "100 g abacaxi", "Hortelã opcional"],
    steps: "Misture e sirva gelado.",
  },
  {
    name: "Hummus com cenoura e pepino",
    category: "Lanche",
    servings: 1,
    prepMinutes: 10,
    kcal: 240,
    protein: 9,
    carbs: 22,
    fat: 12,
    ingredients: ["80 g hummus", "Cenoura e pepino em sticks"],
    steps: "Sirva o hummus com os vegetais crus.",
  },
  {
    name: "Shake de chocolate light",
    category: "Lanche",
    servings: 1,
    prepMinutes: 5,
    kcal: 250,
    protein: 26,
    carbs: 20,
    fat: 5,
    ingredients: ["1 scoop whey chocolate", "200 ml leite desnatado", "Gelo", "Cacau 100% opcional"],
    steps: "Bata tudo e sirva gelado.",
  },
  {
    name: "Torrada integral com atum",
    category: "Lanche",
    servings: 1,
    prepMinutes: 7,
    kcal: 270,
    protein: 24,
    carbs: 22,
    fat: 8,
    ingredients: ["2 torradas integrais", "1 lata atum em água", "Limão", "Cebolinha"],
    steps: "Escorra o atum, tempere e espalhe nas torradas.",
  },
  {
    name: "Gelatina zero com iogurte",
    category: "Lanche",
    servings: 2,
    prepMinutes: 10,
    kcal: 90,
    protein: 10,
    carbs: 6,
    fat: 2,
    ingredients: ["1 pacote gelatina zero", "100 g iogurte natural"],
    steps: "Prepare a gelatina; após firmar, sirva com iogurte.",
  },
  {
    name: "Banana com canela e whey",
    category: "Lanche",
    servings: 1,
    prepMinutes: 3,
    kcal: 230,
    protein: 22,
    carbs: 28,
    fat: 3,
    ingredients: ["1 banana", "1 scoop whey baunilha", "Canela"],
    steps: "Amasse a banana com o whey e polvilhe canela.",
  },

  // —— Almoço ——
  {
    name: "Bowl de frango, arroz e legumes",
    category: "Almoço",
    servings: 1,
    prepMinutes: 25,
    kcal: 520,
    protein: 42,
    carbs: 55,
    fat: 12,
    ingredients: ["120 g peito de frango", "100 g arroz integral", "Brócolis e cenoura", "1 c.chá azeite"],
    steps: "Grelhe o frango, monte o bowl com arroz e legumes.",
  },
  {
    name: "Salada de grão-de-bico",
    category: "Almoço",
    servings: 2,
    prepMinutes: 15,
    kcal: 310,
    protein: 14,
    carbs: 36,
    fat: 12,
    ingredients: ["200 g grão-de-bico", "Tomate, pepino, cebola", "Azeite e limão", "Cheiro-verde"],
    steps: "Misture e tempere. Rende 2 porções.",
  },
  {
    name: "Strogonoff de frango light",
    category: "Almoço",
    servings: 2,
    prepMinutes: 30,
    kcal: 380,
    protein: 35,
    carbs: 18,
    fat: 16,
    ingredients: ["300 g frango", "1 cebola", "100 g champignon", "3 c.sopa iogurte natural", "Extrato de tomate"],
    steps: "Refogue o frango, acrescente molho e iogurte no fim. Sirva com arroz ou batata.",
  },
  {
    name: "Feijoada light (versão enxuta)",
    category: "Almoço",
    servings: 4,
    prepMinutes: 90,
    kcal: 420,
    protein: 28,
    carbs: 45,
    fat: 12,
    ingredients: ["300 g feijão preto", "150 g carne magra", "Couve", "Laranja", "Temperos"],
    steps: "Cozinhe o feijão com carne magra. Sirva com couve e laranja.",
  },
  {
    name: "Tilápia grelhada com purê de batata-doce",
    category: "Almoço",
    servings: 1,
    prepMinutes: 25,
    kcal: 400,
    protein: 38,
    carbs: 35,
    fat: 10,
    ingredients: ["150 g tilápia", "150 g batata-doce", "Limão", "Ervas", "Salada"],
    steps: "Grelhe o peixe; amasse a batata-doce cozida. Sirva com salada.",
  },
  {
    name: "Carne magra acebolada com arroz e feijão",
    category: "Almoço",
    servings: 1,
    prepMinutes: 30,
    kcal: 550,
    protein: 40,
    carbs: 55,
    fat: 14,
    ingredients: ["120 g patinho", "80 g arroz", "80 g feijão", "Cebola", "Salada"],
    steps: "Grelhe a carne acebolada e sirva com arroz, feijão e salada.",
  },
  {
    name: "Macarrão integral ao molho de tomate e frango",
    category: "Almoço",
    servings: 1,
    prepMinutes: 25,
    kcal: 480,
    protein: 36,
    carbs: 55,
    fat: 10,
    ingredients: ["80 g macarrão integral (cru)", "100 g frango", "Molho de tomate caseiro", "Manjericão"],
    steps: "Cozinhe o macarrão, misture com frango e molho.",
  },
  {
    name: "Quinoa com legumes e ovo pochê",
    category: "Almoço",
    servings: 1,
    prepMinutes: 25,
    kcal: 420,
    protein: 22,
    carbs: 45,
    fat: 14,
    ingredients: ["80 g quinoa cozida", "Legumes variados", "1 ovo", "Azeite"],
    steps: "Refogue os legumes, monte com quinoa e finalize com ovo pochê.",
  },
  {
    name: "Hambúrguer caseiro de frango com salada",
    category: "Almoço",
    servings: 1,
    prepMinutes: 20,
    kcal: 390,
    protein: 35,
    carbs: 12,
    fat: 20,
    ingredients: ["150 g frango moído", "Temperos", "Alface, tomate", "1 c.chá azeite"],
    steps: "Modele o hambúrguer, grelhe e sirva no prato com salada (sem pão).",
  },
  {
    name: "Lentilha com arroz e salada",
    category: "Almoço",
    servings: 1,
    prepMinutes: 35,
    kcal: 450,
    protein: 22,
    carbs: 68,
    fat: 8,
    ingredients: ["100 g lentilha cozida", "80 g arroz", "Salada verde", "Azeite"],
    steps: "Cozinhe a lentilha temperada e sirva com arroz e salada.",
  },
  {
    name: "Peito de frango à milanesa airfryer",
    category: "Almoço",
    servings: 1,
    prepMinutes: 30,
    kcal: 410,
    protein: 40,
    carbs: 20,
    fat: 16,
    ingredients: ["150 g peito de frango", "Farinha de aveia", "1 ovo", "Temperos"],
    steps: "Empane com aveia e ovo; asse na airfryer até dourar.",
  },
  {
    name: "Moqueca light de peixe",
    category: "Almoço",
    servings: 2,
    prepMinutes: 40,
    kcal: 360,
    protein: 32,
    carbs: 12,
    fat: 18,
    ingredients: ["300 g peixe branco", "Tomate, pimentão, cebola", "Leite de coco light", "Dendê mínimo ou azeite"],
    steps: "Refogue os legumes, acrescente peixe e leite de coco. Cozinhe em fogo baixo.",
  },
  {
    name: "Risoto de abobrinha com frango",
    category: "Almoço",
    servings: 2,
    prepMinutes: 35,
    kcal: 430,
    protein: 30,
    carbs: 48,
    fat: 12,
    ingredients: ["150 g arroz arbóreo ou integral", "200 g frango", "Abobrinha", "Caldo caseiro"],
    steps: "Refogue, adicione caldo aos poucos até o arroz ficar al dente.",
  },
  {
    name: "Wrap de alface com carne moída",
    category: "Almoço",
    servings: 1,
    prepMinutes: 20,
    kcal: 340,
    protein: 32,
    carbs: 10,
    fat: 18,
    ingredients: ["120 g carne magra moída", "Folhas de alface grandes", "Tomate", "Temperos"],
    steps: "Refogue a carne e sirva enrolada nas folhas de alface.",
  },
  {
    name: "Escondidinho de batata-doce com frango",
    category: "Almoço",
    servings: 2,
    prepMinutes: 40,
    kcal: 400,
    protein: 30,
    carbs: 42,
    fat: 10,
    ingredients: ["300 g batata-doce", "250 g frango desfiado", "Cebola", "Temperos"],
    steps: "Faça o purê, monte camadas com frango e leve ao forno para gratinar.",
  },
  {
    name: "Salada Caesar light com frango",
    category: "Almoço",
    servings: 1,
    prepMinutes: 15,
    kcal: 380,
    protein: 38,
    carbs: 12,
    fat: 18,
    ingredients: ["Alface romana", "120 g frango", "2 c.sopa iogurte + mostarda", "Parmesão ralado (10 g)"],
    steps: "Monte a salada com molho de iogurte e frango grelhado.",
  },
  {
    name: "Arroz de couve-flor com carne",
    category: "Almoço",
    servings: 1,
    prepMinutes: 20,
    kcal: 320,
    protein: 30,
    carbs: 14,
    fat: 16,
    ingredients: ["200 g couve-flor processada", "120 g carne magra", "Alho", "Azeite"],
    steps: "Refogue a carne; acrescente a couve-flor e cozinhe 5–7 min.",
  },
  {
    name: "Yakissoba light de legumes e frango",
    category: "Almoço",
    servings: 2,
    prepMinutes: 25,
    kcal: 390,
    protein: 28,
    carbs: 42,
    fat: 10,
    ingredients: ["Macarrão integral", "Frango", "Repolho, cenoura, brócolis", "Shoyu light"],
    steps: "Salteie os ingredientes e misture o macarrão cozido.",
  },

  // —— Jantar ——
  {
    name: "Salmão com batata-doce e salada",
    category: "Jantar",
    servings: 1,
    prepMinutes: 30,
    kcal: 480,
    protein: 36,
    carbs: 40,
    fat: 18,
    ingredients: ["120 g salmão", "150 g batata-doce", "Folhas + tomate", "Limão e ervas"],
    steps: "Asse a batata-doce, grelhe o salmão e sirva com salada.",
  },
  {
    name: "Sopa de legumes com frango",
    category: "Jantar",
    servings: 2,
    prepMinutes: 35,
    kcal: 280,
    protein: 26,
    carbs: 24,
    fat: 8,
    ingredients: ["200 g frango", "Cenoura, abobrinha, chuchu", "Caldo", "Cheiro-verde"],
    steps: "Cozinhe tudo até os legumes amolecerem; ajuste temperos.",
  },
  {
    name: "Omelete completa jantar",
    category: "Jantar",
    servings: 1,
    prepMinutes: 12,
    kcal: 320,
    protein: 26,
    carbs: 8,
    fat: 20,
    ingredients: ["3 ovos", "Tomate e cebola", "Espinafre", "30 g queijo light"],
    steps: "Refogue os legumes, acrescente os ovos e o queijo.",
  },
  {
    name: "Peixe assado com legumes no forno",
    category: "Jantar",
    servings: 1,
    prepMinutes: 35,
    kcal: 360,
    protein: 34,
    carbs: 20,
    fat: 14,
    ingredients: ["150 g peixe", "Abobrinha, berinjela, pimentão", "Azeite", "Ervas"],
    steps: "Disponha tudo na assadeira e asse a 200 °C por ~25 min.",
  },
  {
    name: "Frango desfiado com salada colorida",
    category: "Jantar",
    servings: 1,
    prepMinutes: 20,
    kcal: 340,
    protein: 40,
    carbs: 12,
    fat: 12,
    ingredients: ["150 g frango desfiado", "Mix de folhas", "Cenoura ralada", "Azeite e limão"],
    steps: "Tempere o frango e monte a salada.",
  },
  {
    name: "Caldo verde light",
    category: "Jantar",
    servings: 3,
    prepMinutes: 40,
    kcal: 220,
    protein: 12,
    carbs: 28,
    fat: 6,
    ingredients: ["Batata", "Couve", "50 g linguiça de frango ou omitir", "Alho"],
    steps: "Cozinhe e amasse as batatas; acrescente couve no fim.",
  },
  {
    name: "Berinjela recheada com carne magra",
    category: "Jantar",
    servings: 2,
    prepMinutes: 45,
    kcal: 300,
    protein: 24,
    carbs: 16,
    fat: 14,
    ingredients: ["2 berinjelas", "200 g carne magra moída", "Molho de tomate", "Queijo light"],
    steps: "Asse as berinjelas, recheie e gratinar.",
  },
  {
    name: "Tofu grelhado com legumes",
    category: "Jantar",
    servings: 1,
    prepMinutes: 20,
    kcal: 310,
    protein: 22,
    carbs: 18,
    fat: 16,
    ingredients: ["150 g tofu firme", "Brócolis e pimentão", "Shoyu light", "Gergelim"],
    steps: "Grelhe o tofu e salteie os legumes.",
  },
  {
    name: "Panqueca de frango integral",
    category: "Jantar",
    servings: 2,
    prepMinutes: 30,
    kcal: 360,
    protein: 28,
    carbs: 32,
    fat: 12,
    ingredients: ["Massa: ovo + aveia + leite", "Recheio: frango desfiado", "Molho de tomate"],
    steps: "Faça as panquecas, recheie e leve ao forno com molho.",
  },
  {
    name: "Salada de atum mediterrânea",
    category: "Jantar",
    servings: 1,
    prepMinutes: 10,
    kcal: 330,
    protein: 30,
    carbs: 14,
    fat: 16,
    ingredients: ["1 lata atum", "Tomate cereja", "Azeitona (poucas)", "Folhas", "Azeite"],
    steps: "Misture e tempere com limão e azeite.",
  },
  {
    name: "Abobrinha spaghetti com molho bolonhesa",
    category: "Jantar",
    servings: 1,
    prepMinutes: 25,
    kcal: 290,
    protein: 28,
    carbs: 16,
    fat: 12,
    ingredients: ["2 abobrinhas em fio", "120 g carne magra", "Molho de tomate"],
    steps: "Refogue a carne no molho; salteie a abobrinha 3 min e misture.",
  },
  {
    name: "Sardinha assada com batata e salada",
    category: "Jantar",
    servings: 1,
    prepMinutes: 30,
    kcal: 420,
    protein: 32,
    carbs: 30,
    fat: 18,
    ingredients: ["120 g sardinha fresca ou em água", "Batata cozida", "Salada", "Limão"],
    steps: "Asse/grelhe a sardinha e sirva com batata e salada.",
  },

  // —— Pré/pós treino & extras ——
  {
    name: "Batata-doce com ovo cozido",
    category: "Pré-treino",
    servings: 1,
    prepMinutes: 20,
    kcal: 300,
    protein: 14,
    carbs: 40,
    fat: 8,
    ingredients: ["150 g batata-doce", "2 ovos cozidos", "Sal"],
    steps: "Asse ou cozinhe a batata; sirva com os ovos.",
  },
  {
    name: "Pão sírio com pasta de grão-de-bico e frango",
    category: "Pré-treino",
    servings: 1,
    prepMinutes: 10,
    kcal: 380,
    protein: 30,
    carbs: 40,
    fat: 10,
    ingredients: ["1 pão sírio integral", "2 c.sopa hummus", "80 g frango"],
    steps: "Monte o sanduíche e aqueça se desejar.",
  },
  {
    name: "Mingau de cream rice (pós-treino)",
    category: "Pós-treino",
    servings: 1,
    prepMinutes: 10,
    kcal: 360,
    protein: 32,
    carbs: 48,
    fat: 4,
    ingredients: ["40 g cream rice ou arroz cremoso", "1 scoop whey", "Água ou leite"],
    steps: "Cozinhe o cream rice e misture o whey fora do fogo.",
  },
  {
    name: "Açaí bowl fitness (versão controlada)",
    category: "Lanche",
    servings: 1,
    prepMinutes: 8,
    kcal: 350,
    protein: 20,
    carbs: 45,
    fat: 10,
    ingredients: ["100 g polpa açaí sem xarope", "1 scoop whey", "Granola light 20 g", "Banana"],
    steps: "Bata o açaí com whey; cubra com granola e fruta.",
  },
  {
    name: "Risoto de frango com brócolis",
    category: "Almoço",
    servings: 2,
    prepMinutes: 40,
    kcal: 440,
    protein: 32,
    carbs: 50,
    fat: 12,
    ingredients: ["Arroz arbóreo", "Frango", "Brócolis", "Caldo"],
    steps: "Prepare como risoto clássico, adicionando brócolis no fim.",
  },
  {
    name: "Tabule de quinoa",
    category: "Lanche",
    servings: 2,
    prepMinutes: 20,
    kcal: 260,
    protein: 10,
    carbs: 32,
    fat: 10,
    ingredients: ["Quinoa", "Tomate", "Pepino", "Hortelã", "Limão e azeite"],
    steps: "Misture a quinoa cozida fria com os vegetais e tempere.",
  },
  {
    name: "Frango teriyaki light",
    category: "Almoço",
    servings: 1,
    prepMinutes: 25,
    kcal: 400,
    protein: 40,
    carbs: 28,
    fat: 10,
    ingredients: ["150 g frango", "Shoyu light", "Mel (1 c.chá)", "Gengibre", "Arroz 80 g"],
    steps: "Marine e grelhe o frango; sirva com arroz.",
  },
  {
    name: "Sopa creme de abóbora com frango",
    category: "Jantar",
    servings: 2,
    prepMinutes: 35,
    kcal: 260,
    protein: 22,
    carbs: 28,
    fat: 6,
    ingredients: ["Abóbora", "150 g frango", "Cebola", "Gengibre opcional"],
    steps: "Cozinhe e bata a abóbora; acrescente frango desfiado.",
  },
  {
    name: "Ovos mexidos com batata-doce hash",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 15,
    kcal: 340,
    protein: 20,
    carbs: 32,
    fat: 14,
    ingredients: ["2 ovos", "100 g batata-doce em cubos", "Páprica", "Azeite"],
    steps: "Doure a batata-doce, acrescente os ovos mexidos.",
  },
  {
    name: "Salada de feijão-branco com atum",
    category: "Almoço",
    servings: 1,
    prepMinutes: 10,
    kcal: 390,
    protein: 34,
    carbs: 36,
    fat: 10,
    ingredients: ["150 g feijão-branco", "1 lata atum", "Cebola roxa", "Azeite e limão"],
    steps: "Misture e tempere. Pronto em 10 minutos.",
  },
  {
    name: "Nhoque de batata-doce com molho de tomate",
    category: "Jantar",
    servings: 2,
    prepMinutes: 50,
    kcal: 380,
    protein: 14,
    carbs: 62,
    fat: 8,
    ingredients: ["Batata-doce", "Farinha de trigo ou aveia", "Molho de tomate", "Manjericão"],
    steps: "Faça a massa, cozinhe os nhoques e sirva com molho.",
  },
  {
    name: "Bowl mexicano light (frango e feijão)",
    category: "Almoço",
    servings: 1,
    prepMinutes: 25,
    kcal: 480,
    protein: 38,
    carbs: 48,
    fat: 12,
    ingredients: ["Frango", "Feijão", "Milho", "Tomate", "Alface", "Iogurte no lugar de sour cream"],
    steps: "Monte o bowl com todos os ingredientes temperados.",
  },
  {
    name: "Camarão alho e óleo com abobrinha",
    category: "Jantar",
    servings: 1,
    prepMinutes: 20,
    kcal: 300,
    protein: 32,
    carbs: 10,
    fat: 14,
    ingredients: ["150 g camarão", "Abobrinha", "Alho", "Azeite", "Salsinha"],
    steps: "Salteie o alho, o camarão e a abobrinha rapidamente.",
  },
  {
    name: "Panqueca americana proteica",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 15,
    kcal: 330,
    protein: 28,
    carbs: 30,
    fat: 10,
    ingredients: ["2 ovos", "30 g aveia", "1 scoop whey", "Fermento", "Frutas"],
    steps: "Bata a massa e frite panquecas pequenas; sirva com fruta.",
  },
  {
    name: "Salada de batata com frango (sem maionese)",
    category: "Almoço",
    servings: 2,
    prepMinutes: 30,
    kcal: 350,
    protein: 28,
    carbs: 32,
    fat: 10,
    ingredients: ["Batata", "Frango", "Iogurte natural", "Mostarda", "Ervilha"],
    steps: "Misture com molho de iogurte e mostarda.",
  },
  {
    name: "Espetinho de frango com legumes",
    category: "Jantar",
    servings: 1,
    prepMinutes: 30,
    kcal: 340,
    protein: 36,
    carbs: 16,
    fat: 12,
    ingredients: ["150 g frango em cubos", "Pimentão", "Cebola", "Abobrinha"],
    steps: "Monte os espetos e grelhe/asse até dourar.",
  },
  {
    name: "Arroz integral com ovo e legumes",
    category: "Almoço",
    servings: 1,
    prepMinutes: 20,
    kcal: 420,
    protein: 18,
    carbs: 55,
    fat: 12,
    ingredients: ["100 g arroz integral", "1 ovo", "Legumes salteados", "Shoyu light"],
    steps: "Salteie o arroz com legumes e finalize com ovo.",
  },
  {
    name: "Cottage bowl com tomate e orégano",
    category: "Lanche",
    servings: 1,
    prepMinutes: 5,
    kcal: 180,
    protein: 20,
    carbs: 8,
    fat: 7,
    ingredients: ["150 g cottage", "Tomate cereja", "Orégano", "Azeite (fio)"],
    steps: "Misture e sirva imediatamente.",
  },
  {
    name: "Sopa de lentilha",
    category: "Jantar",
    servings: 3,
    prepMinutes: 45,
    kcal: 290,
    protein: 18,
    carbs: 40,
    fat: 6,
    ingredients: ["Lentilha", "Cenoura", "Cebola", "Alho", "Cominho"],
    steps: "Cozinhe até amolecer; ajuste água e temperos.",
  },
  {
    name: "Frango xadrez light",
    category: "Almoço",
    servings: 2,
    prepMinutes: 30,
    kcal: 370,
    protein: 34,
    carbs: 22,
    fat: 14,
    ingredients: ["Frango", "Pimentões", "Castanha-de-caju (poucas)", "Shoyu light"],
    steps: "Salteie em fogo alto e sirva com arroz se desejar.",
  },
  {
    name: "Purê de couve-flor com almôndegas de frango",
    category: "Jantar",
    servings: 2,
    prepMinutes: 40,
    kcal: 340,
    protein: 32,
    carbs: 14,
    fat: 16,
    ingredients: ["Couve-flor", "Frango moído", "Temperos", "Molho de tomate"],
    steps: "Faça as almôndegas, asse; sirva sobre o purê de couve-flor.",
  },
  {
    name: "Sanduíche natural de frango",
    category: "Lanche",
    servings: 1,
    prepMinutes: 10,
    kcal: 320,
    protein: 26,
    carbs: 30,
    fat: 10,
    ingredients: ["Pão integral", "Frango desfiado", "Cenoura ralada", "Iogurte no lugar de maionese"],
    steps: "Misture o recheio e monte o sanduíche.",
  },
  {
    name: "Peixe ensopado com legumes",
    category: "Jantar",
    servings: 2,
    prepMinutes: 35,
    kcal: 300,
    protein: 32,
    carbs: 16,
    fat: 10,
    ingredients: ["Peixe branco", "Tomate", "Pimentão", "Cebola", "Coentro"],
    steps: "Cozinhe em fogo baixo no molho de legumes.",
  },
  {
    name: "Bowl de atum, arroz e abacate",
    category: "Almoço",
    servings: 1,
    prepMinutes: 15,
    kcal: 500,
    protein: 32,
    carbs: 48,
    fat: 18,
    ingredients: ["1 lata atum", "100 g arroz", "1/4 abacate", "Gergelim", "Shoyu light"],
    steps: "Monte o bowl e tempere.",
  },
  {
    name: "Chips de batata-doce no forno",
    category: "Lanche",
    servings: 2,
    prepMinutes: 35,
    kcal: 160,
    protein: 2,
    carbs: 32,
    fat: 3,
    ingredients: ["1 batata-doce", "Páprica", "Sal", "Spray de azeite"],
    steps: "Fatie fino, tempere e asse até crocante.",
  },
  {
    name: "Omelete de forno (meal prep)",
    category: "Café da manhã",
    servings: 4,
    prepMinutes: 35,
    kcal: 200,
    protein: 16,
    carbs: 4,
    fat: 12,
    ingredients: ["8 ovos", "Espinafre", "Tomate", "Queijo light"],
    steps: "Misture, despeje em forma e asse. Porcione para a semana.",
  },
  {
    name: "Salada de macarrão integral fria",
    category: "Almoço",
    servings: 2,
    prepMinutes: 25,
    kcal: 400,
    protein: 18,
    carbs: 55,
    fat: 10,
    ingredients: ["Macarrão integral", "Frango ou atum", "Legumes", "Molho de iogurte"],
    steps: "Cozinhe, esfrie, misture os demais ingredientes.",
  },
  {
    name: "Lombo suíno grelhado com salada",
    category: "Almoço",
    servings: 1,
    prepMinutes: 25,
    kcal: 410,
    protein: 38,
    carbs: 8,
    fat: 22,
    ingredients: ["140 g lombo suíno", "Salada", "Limão", "Alho"],
    steps: "Grelhe o lombo e sirva com salada abundante.",
  },
  {
    name: "Smoothie bowl de manga e whey",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 8,
    kcal: 340,
    protein: 28,
    carbs: 42,
    fat: 5,
    ingredients: ["Manga congelada", "1 scoop whey", "Iogurte", "Granola 15 g"],
    steps: "Bata grosso, sirva em tigela com granola.",
  },
  {
    name: "Guisado de grão-de-bico com espinafre",
    category: "Jantar",
    servings: 2,
    prepMinutes: 30,
    kcal: 330,
    protein: 16,
    carbs: 40,
    fat: 10,
    ingredients: ["Grão-de-bico", "Espinafre", "Tomate", "Cominho", "Alho"],
    steps: "Refogue temperos, acrescente grão-de-bico e espinafre.",
  },
  {
    name: "Frango ao curry light com arroz",
    category: "Almoço",
    servings: 2,
    prepMinutes: 35,
    kcal: 460,
    protein: 36,
    carbs: 48,
    fat: 12,
    ingredients: ["Frango", "Curry", "Iogurte ou leite de coco light", "Arroz"],
    steps: "Cozinhe o frango no molho de curry e sirva com arroz.",
  },
  {
    name: "Salada de ovo e batata",
    category: "Lanche",
    servings: 1,
    prepMinutes: 20,
    kcal: 300,
    protein: 16,
    carbs: 28,
    fat: 12,
    ingredients: ["2 ovos", "1 batata média", "Mostarda", "Cebolinha"],
    steps: "Cozinhe, pique e tempere sem maionese.",
  },
  {
    name: "Poke bowl light (salmão)",
    category: "Almoço",
    servings: 1,
    prepMinutes: 20,
    kcal: 520,
    protein: 34,
    carbs: 50,
    fat: 18,
    ingredients: ["100 g salmão", "Arroz", "Pepino", "Edamame ou ervilha", "Gergelim"],
    steps: "Monte o poke com base de arroz e coberturas.",
  },
  {
    name: "Canja de galinha light",
    category: "Jantar",
    servings: 3,
    prepMinutes: 45,
    kcal: 240,
    protein: 20,
    carbs: 28,
    fat: 5,
    ingredients: ["Frango", "Arroz", "Cenoura", "Batata", "Cheiro-verde"],
    steps: "Cozinhe o frango, acrescente arroz e legumes até engrossar.",
  },
  {
    name: "Tosta de ricota com tomate e manjericão",
    category: "Lanche",
    servings: 1,
    prepMinutes: 8,
    kcal: 250,
    protein: 14,
    carbs: 24,
    fat: 10,
    ingredients: ["Pão integral", "Ricota", "Tomate", "Manjericão", "Azeite"],
    steps: "Torre o pão e monte a bruschetta light.",
  },
  {
    name: "Almôndegas de carne magra no molho",
    category: "Almoço",
    servings: 2,
    prepMinutes: 40,
    kcal: 380,
    protein: 34,
    carbs: 18,
    fat: 18,
    ingredients: ["Carne magra moída", "Aveia", "Ovo", "Molho de tomate"],
    steps: "Modele, asse e finalize no molho.",
  },
  {
    name: "Ceviche de tilápia",
    category: "Jantar",
    servings: 2,
    prepMinutes: 25,
    kcal: 220,
    protein: 28,
    carbs: 10,
    fat: 6,
    ingredients: ["Tilápia", "Limão", "Cebola roxa", "Coentro", "Pimenta"],
    steps: "Marine o peixe no limão até “cozinhar”; misture os temperos.",
  },
  {
    name: "Bowl de tofu scramble",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 12,
    kcal: 280,
    protein: 20,
    carbs: 16,
    fat: 14,
    ingredients: ["150 g tofu", "Cúrcuma", "Espinafre", "Tomate"],
    steps: "Esmague e refogue o tofu como ovos mexidos.",
  },
  {
    name: "Espaguete de cenoura com frango",
    category: "Jantar",
    servings: 1,
    prepMinutes: 20,
    kcal: 310,
    protein: 32,
    carbs: 20,
    fat: 10,
    ingredients: ["Cenoura em fio", "Frango", "Molho de tomate", "Manjericão"],
    steps: "Salteie a cenoura 3–4 min e misture ao frango com molho.",
  },
  {
    name: "Cookies proteicos de banana",
    category: "Lanche",
    servings: 6,
    prepMinutes: 25,
    kcal: 120,
    protein: 8,
    carbs: 14,
    fat: 3,
    ingredients: ["2 bananas", "2 scoops whey", "Aveia", "Canela"],
    steps: "Amasse, modele cookies e asse ~15 min a 180 °C.",
  },
  {
    name: "Sopa de tomate com grão-de-bico",
    category: "Jantar",
    servings: 2,
    prepMinutes: 30,
    kcal: 270,
    protein: 12,
    carbs: 36,
    fat: 8,
    ingredients: ["Tomate", "Grão-de-bico", "Alho", "Manjericão", "Azeite"],
    steps: "Cozinhe, bata parte do caldo e misture o grão-de-bico.",
  },
  {
    name: "Frango à passarinho airfryer",
    category: "Almoço",
    servings: 2,
    prepMinutes: 35,
    kcal: 400,
    protein: 38,
    carbs: 4,
    fat: 24,
    ingredients: ["Coxinha da asa sem pele", "Alho", "Limão", "Páprica"],
    steps: "Tempere e asse na airfryer até crocante.",
  },
  {
    name: "Bowl de ricota, melancia e hortelã",
    category: "Lanche",
    servings: 1,
    prepMinutes: 5,
    kcal: 200,
    protein: 12,
    carbs: 18,
    fat: 8,
    ingredients: ["100 g ricota", "Melancia", "Hortelã", "Limão"],
    steps: "Monte o bowl fresco — ideal no calor.",
  },
  {
    name: "Arroz de forno light com frango e brócolis",
    category: "Almoço",
    servings: 3,
    prepMinutes: 45,
    kcal: 420,
    protein: 30,
    carbs: 48,
    fat: 10,
    ingredients: ["Arroz cozido", "Frango", "Brócolis", "Molho de tomate", "Queijo light"],
    steps: "Misture, coloque em travessa e gratinar.",
  },
  {
    name: "Panqueca de batata-doce recheada",
    category: "Jantar",
    servings: 2,
    prepMinutes: 30,
    kcal: 350,
    protein: 24,
    carbs: 40,
    fat: 10,
    ingredients: ["Batata-doce", "Ovo", "Recheio de frango", "Temperos"],
    steps: "Faça a massa de batata-doce + ovo, recheie e aqueça.",
  },
  {
    name: "Salada de lentilha com feta light",
    category: "Almoço",
    servings: 2,
    prepMinutes: 20,
    kcal: 340,
    protein: 18,
    carbs: 38,
    fat: 12,
    ingredients: ["Lentilha", "Queijo light tipo feta", "Rúcula", "Tomate", "Azeite"],
    steps: "Misture a lentilha fria com os demais ingredientes.",
  },
  {
    name: "Shake café da manhã (café + whey)",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 5,
    kcal: 240,
    protein: 28,
    carbs: 12,
    fat: 6,
    ingredients: ["Café frio", "1 scoop whey", "Leite desnatado", "Gelo"],
    steps: "Bata tudo — versão gelada tipo iced protein coffee.",
  },
  {
    name: "Ratatouille com ovo",
    category: "Jantar",
    servings: 2,
    prepMinutes: 40,
    kcal: 250,
    protein: 12,
    carbs: 22,
    fat: 12,
    ingredients: ["Berinjela", "Abobrinha", "Tomate", "Pimentão", "2 ovos"],
    steps: "Asse os legumes em camadas; finalize com ovos no forno.",
  },
  {
    name: "Kibe assado de forno",
    category: "Almoço",
    servings: 4,
    prepMinutes: 50,
    kcal: 320,
    protein: 22,
    carbs: 28,
    fat: 12,
    ingredients: ["Trigo para kibe", "Carne magra", "Hortelã", "Cebola"],
    steps: "Hidrate o trigo, misture, asse em forma untada.",
  },
  {
    name: "Salada de frutos do mar",
    category: "Jantar",
    servings: 2,
    prepMinutes: 25,
    kcal: 280,
    protein: 30,
    carbs: 10,
    fat: 12,
    ingredients: ["Camarão", "Lula ou peixe", "Folhas", "Limão", "Azeite"],
    steps: "Cozinhe os frutos do mar e misture à salada.",
  },
  {
    name: "Pão de queijo na airfryer (porção)",
    category: "Lanche",
    servings: 1,
    prepMinutes: 15,
    kcal: 220,
    protein: 8,
    carbs: 24,
    fat: 10,
    ingredients: ["Massa pronta light ou caseira (2–3 un.)"],
    steps: "Asse na airfryer até dourar. Controle a porção.",
  },
  {
    name: "Chili de carne magra com feijão",
    category: "Almoço",
    servings: 3,
    prepMinutes: 45,
    kcal: 400,
    protein: 32,
    carbs: 36,
    fat: 12,
    ingredients: ["Carne magra", "Feijão", "Tomate", "Pimentão", "Cominho e páprica"],
    steps: "Refogue e cozinhe até engrossar. Sirva só ou com arroz.",
  },
  {
    name: "Wrap de omelete (sem farinha)",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 10,
    kcal: 280,
    protein: 24,
    carbs: 6,
    fat: 16,
    ingredients: ["3 ovos", "Folhas", "Tomate", "Peito de peru"],
    steps: "Faça uma omelete fina e use como wrap.",
  },
  {
    name: "Sopa miso com tofu e vegetais",
    category: "Jantar",
    servings: 1,
    prepMinutes: 15,
    kcal: 180,
    protein: 14,
    carbs: 16,
    fat: 6,
    ingredients: ["Pasta miso", "Tofu", "Alga", "Shitake ou vegetais"],
    steps: "Dissolva o miso em água quente (não fervendo); acrescente tofu.",
  },
  {
    name: "Frango crocante com farinha de amêndoas",
    category: "Almoço",
    servings: 1,
    prepMinutes: 30,
    kcal: 420,
    protein: 42,
    carbs: 8,
    fat: 22,
    ingredients: ["Peito de frango", "Farinha de amêndoas", "Ovo", "Temperos"],
    steps: "Empane e asse/airfryer até dourar.",
  },
  {
    name: "Salada grega light",
    category: "Lanche",
    servings: 1,
    prepMinutes: 10,
    kcal: 260,
    protein: 12,
    carbs: 14,
    fat: 18,
    ingredients: ["Pepino", "Tomate", "Cebola roxa", "Queijo light", "Azeitona (poucas)", "Azeite"],
    steps: "Pique, misture e tempere com orégano e limão.",
  },
  {
    name: "Risoto de funghi light",
    category: "Jantar",
    servings: 2,
    prepMinutes: 40,
    kcal: 400,
    protein: 12,
    carbs: 62,
    fat: 10,
    ingredients: ["Arroz arbóreo", "Cogumelos", "Caldo", "Queijo light"],
    steps: "Prepare o risoto clássico com pouco queijo no fim.",
  },
  {
    name: "Bowl de proteína vegetal (grão-de-bico + quinoa)",
    category: "Almoço",
    servings: 1,
    prepMinutes: 25,
    kcal: 450,
    protein: 20,
    carbs: 58,
    fat: 14,
    ingredients: ["Quinoa", "Grão-de-bico", "Legumes assados", "Tahine light ou azeite"],
    steps: "Monte o bowl e regue com molho de tahine diluído.",
  },
  {
    name: "Omelete de forno muffin (unitário)",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 25,
    kcal: 160,
    protein: 14,
    carbs: 2,
    fat: 10,
    ingredients: ["2 ovos", "Espinafre", "Tomate", "Sal"],
    steps: "Asse em formia xícara ou forma de muffin ~18 min.",
  },
  {
    name: "Tilápia à milanesa de aveia",
    category: "Jantar",
    servings: 1,
    prepMinutes: 25,
    kcal: 360,
    protein: 36,
    carbs: 18,
    fat: 14,
    ingredients: ["Filé de tilápia", "Aveia", "Ovo", "Limão"],
    steps: "Empane e asse até dourar.",
  },
  {
    name: "Vitamina marrom (mamão, aveia, linhaça)",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 5,
    kcal: 280,
    protein: 10,
    carbs: 45,
    fat: 7,
    ingredients: ["Mamão", "Aveia", "Linhaça", "Leite desnatado"],
    steps: "Bata tudo no liquidificador.",
  },
  {
    name: "Carne de panela light com legumes",
    category: "Almoço",
    servings: 3,
    prepMinutes: 90,
    kcal: 380,
    protein: 34,
    carbs: 20,
    fat: 16,
    ingredients: ["Músculo ou acém", "Cenoura", "Batata", "Cebola", "Temperos"],
    steps: "Cozinhe na pressão até a carne desmanchar.",
  },
  {
    name: "Salada de quinoa com frango e manga",
    category: "Almoço",
    servings: 1,
    prepMinutes: 20,
    kcal: 440,
    protein: 34,
    carbs: 42,
    fat: 12,
    ingredients: ["Quinoa", "Frango", "Manga", "Rúcula", "Limão"],
    steps: "Misture tudo e tempere na hora de servir.",
  },
  {
    name: "Panqueca de whey 3 ingredientes",
    category: "Lanche",
    servings: 1,
    prepMinutes: 8,
    kcal: 220,
    protein: 30,
    carbs: 8,
    fat: 6,
    ingredients: ["1 scoop whey", "1 ovo", "1 clara", "Canela"],
    steps: "Bata e frite como panqueca fina.",
  },
  {
    name: "Sopa de ervilha com frango",
    category: "Jantar",
    servings: 3,
    prepMinutes: 50,
    kcal: 300,
    protein: 24,
    carbs: 32,
    fat: 6,
    ingredients: ["Ervilha seca", "Frango", "Cenoura", "Cebola"],
    steps: "Cozinhe a ervilha até cremosa; acrescente frango desfiado.",
  },
  {
    name: "Tacos de alface com picadillo",
    category: "Jantar",
    servings: 1,
    prepMinutes: 20,
    kcal: 330,
    protein: 30,
    carbs: 12,
    fat: 16,
    ingredients: ["Carne magra moída", "Alface americana", "Tomate", "Cominho"],
    steps: "Recheie as folhas de alface com a carne temperada.",
  },
  {
    name: "Bowl açaí banana whey (sem granola)",
    category: "Pós-treino",
    servings: 1,
    prepMinutes: 5,
    kcal: 300,
    protein: 26,
    carbs: 38,
    fat: 5,
    ingredients: ["Polpa açaí sem açúcar", "Banana", "Whey"],
    steps: "Bata e sirva imediatamente.",
  },
  {
    name: "Gratinado de brócolis com frango",
    category: "Jantar",
    servings: 2,
    prepMinutes: 35,
    kcal: 340,
    protein: 36,
    carbs: 12,
    fat: 14,
    ingredients: ["Brócolis", "Frango", "Molho branco de iogurte", "Queijo light"],
    steps: "Monte, regue o molho e gratinar.",
  },
  {
    name: "Pastel de forno de frango (massa integral)",
    category: "Lanche",
    servings: 2,
    prepMinutes: 40,
    kcal: 280,
    protein: 20,
    carbs: 28,
    fat: 8,
    ingredients: ["Massa integral", "Frango desfiado", "Temperos"],
    steps: "Recheie, feche e asse até dourar.",
  },
  {
    name: "Salmão poke low carb (base de pepino)",
    category: "Jantar",
    servings: 1,
    prepMinutes: 15,
    kcal: 360,
    protein: 32,
    carbs: 12,
    fat: 20,
    ingredients: ["Salmão", "Pepino em cubos", "Abacate", "Gergelim", "Shoyu light"],
    steps: "Substitua o arroz por pepino e monte o poke.",
  },
  {
    name: "Mingau de quinoa com maçã",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 15,
    kcal: 310,
    protein: 12,
    carbs: 48,
    fat: 8,
    ingredients: ["Quinoa", "Maçã", "Canela", "Leite desnatado"],
    steps: "Cozinhe a quinoa no leite com maçã e canela.",
  },
  {
    name: "Frango marsala light",
    category: "Almoço",
    servings: 2,
    prepMinutes: 30,
    kcal: 360,
    protein: 38,
    carbs: 10,
    fat: 16,
    ingredients: ["Filé de frango", "Cogumelos", "Caldo", "Vinho ou vinagre balsâmico"],
    steps: "Sele o frango, prepare o molho com cogumelos e reduza.",
  },
  {
    name: "Salada de grãos (feijão + milho + atum)",
    category: "Almoço",
    servings: 1,
    prepMinutes: 10,
    kcal: 400,
    protein: 32,
    carbs: 40,
    fat: 10,
    ingredients: ["Feijão", "Milho", "Atum", "Cebola", "Limão"],
    steps: "Escorra, misture e tempere. Meal prep frio.",
  },
  {
    name: "Ovos benedict light (sem molho holandês)",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 15,
    kcal: 320,
    protein: 22,
    carbs: 22,
    fat: 14,
    ingredients: ["2 ovos pochê", "Pão integral", "Peito de peru", "Iogurte + mostarda"],
    steps: "Monte o sanduíche aberto com molho de iogurte.",
  },
  {
    name: "Moqueca de banana-da-terra com peixe",
    category: "Almoço",
    servings: 2,
    prepMinutes: 40,
    kcal: 380,
    protein: 30,
    carbs: 32,
    fat: 14,
    ingredients: ["Peixe", "Banana-da-terra", "Leite de coco light", "Dendê mínimo", "Coentro"],
    steps: "Cozinhe peixe e banana no molho de coco e temperos.",
  },
  {
    name: "Bowl de cottage, manga e chia",
    category: "Lanche",
    servings: 1,
    prepMinutes: 5,
    kcal: 240,
    protein: 22,
    carbs: 24,
    fat: 6,
    ingredients: ["Cottage", "Manga", "1 c.sopa chia"],
    steps: "Misture e deixe a chia hidratar 5 minutos.",
  },
  {
    name: "Espetinho misto (frango + legumes) airfryer",
    category: "Jantar",
    servings: 1,
    prepMinutes: 25,
    kcal: 330,
    protein: 34,
    carbs: 14,
    fat: 12,
    ingredients: ["Frango", "Abobrinha", "Pimentão", "Cebola"],
    steps: "Tempere, monte e asse na airfryer ~15 min.",
  },
  {
    name: "Sopa creme de cenoura com gengibre",
    category: "Jantar",
    servings: 2,
    prepMinutes: 30,
    kcal: 180,
    protein: 4,
    carbs: 28,
    fat: 6,
    ingredients: ["Cenoura", "Gengibre", "Cebola", "Caldo", "Azeite"],
    steps: "Cozinhe, bata e ajuste o tempero. Opcional: whey neutro.",
  },
  {
    name: "Pizza de frigideira low carb",
    category: "Jantar",
    servings: 1,
    prepMinutes: 15,
    kcal: 380,
    protein: 32,
    carbs: 10,
    fat: 22,
    ingredients: ["2 ovos + 2 claras", "Molho de tomate", "Queijo light", "Orégano"],
    steps: "Faça a base de omelete, cubra e derreta o queijo.",
  },
  {
    name: "Bowl mediterrâneo (frango, homus, salada)",
    category: "Almoço",
    servings: 1,
    prepMinutes: 20,
    kcal: 470,
    protein: 38,
    carbs: 32,
    fat: 18,
    ingredients: ["Frango", "Hummus", "Pepino", "Tomate", "Folhas"],
    steps: "Monte o bowl com todos os componentes.",
  },
  {
    name: "Pudim de chia proteico",
    category: "Lanche",
    servings: 2,
    prepMinutes: 10,
    kcal: 220,
    protein: 18,
    carbs: 18,
    fat: 8,
    ingredients: ["Chia", "Leite desnatado", "Whey", "Essência de baunilha"],
    steps: "Misture e leve à geladeira por 4 h.",
  },
  {
    name: "Bife de patinho com legumes salteados",
    category: "Almoço",
    servings: 1,
    prepMinutes: 20,
    kcal: 400,
    protein: 40,
    carbs: 14,
    fat: 18,
    ingredients: ["140 g patinho", "Abobrinha", "Cenoura", "Alho"],
    steps: "Grelhe o bife e salteie os legumes.",
  },
  {
    name: "Caldinho de feijão com couve",
    category: "Jantar",
    servings: 2,
    prepMinutes: 25,
    kcal: 250,
    protein: 14,
    carbs: 36,
    fat: 4,
    ingredients: ["Feijão cozido", "Couve", "Alho", "Cominho"],
    steps: "Bata parte do feijão, aqueça com couve refogada.",
  },
  {
    name: "Torta salgada de liquidificador light",
    category: "Almoço",
    servings: 6,
    prepMinutes: 50,
    kcal: 280,
    protein: 16,
    carbs: 24,
    fat: 12,
    ingredients: ["Ovos", "Aveia", "Leite desnatado", "Recheio de frango ou legumes"],
    steps: "Bata a massa, coloque o recheio e asse.",
  },
  {
    name: "Ceviche de manga com camarão",
    category: "Lanche",
    servings: 2,
    prepMinutes: 20,
    kcal: 200,
    protein: 18,
    carbs: 18,
    fat: 4,
    ingredients: ["Camarão", "Manga", "Cebola roxa", "Limão", "Coentro"],
    steps: "Misture o camarão cozido com manga e temperos ácidos.",
  },
  {
    name: "Bowl de batata-doce, ovos e abacate",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 20,
    kcal: 420,
    protein: 18,
    carbs: 40,
    fat: 20,
    ingredients: ["Batata-doce", "2 ovos", "1/4 abacate", "Páprica"],
    steps: "Asse a batata, frite/cozinhe os ovos e monte o bowl.",
  },
  {
    name: "Salmão airfryer com aspargos",
    category: "Jantar",
    servings: 1,
    prepMinutes: 20,
    kcal: 400,
    protein: 34,
    carbs: 8,
    fat: 24,
    ingredients: ["Salmão", "Aspargos", "Limão", "Azeite", "Ervas"],
    steps: "Tempere e asse na airfryer ~12–15 min.",
  },
  {
    name: "Couscous marroquino com frango",
    category: "Almoço",
    servings: 2,
    prepMinutes: 25,
    kcal: 430,
    protein: 30,
    carbs: 48,
    fat: 10,
    ingredients: ["Cuscuz marroquino ou quinoa", "Frango", "Vegetais", "Cominho"],
    steps: "Hidrate o cuscuz e misture com frango e legumes.",
  },
  {
    name: "Barra caseira de tâmaras e castanhas",
    category: "Lanche",
    servings: 8,
    prepMinutes: 20,
    kcal: 140,
    protein: 3,
    carbs: 18,
    fat: 7,
    ingredients: ["Tâmaras", "Castanhas", "Aveia", "Cacau opcional"],
    steps: "Processe, modele barras e leve à geladeira.",
  },
  {
    name: "Moqueca light de palmito e tomate",
    category: "Jantar",
    servings: 2,
    prepMinutes: 30,
    kcal: 220,
    protein: 6,
    carbs: 18,
    fat: 14,
    ingredients: ["Palmito", "Tomate", "Pimentão", "Leite de coco light", "Coentro"],
    steps: "Refogue e cozinhe em fogo baixo. Opção vegetariana.",
  },
  {
    name: "Bowl de frango crocante e salada asiática",
    category: "Almoço",
    servings: 1,
    prepMinutes: 25,
    kcal: 450,
    protein: 40,
    carbs: 30,
    fat: 16,
    ingredients: ["Frango empanado aveia", "Repolho", "Cenoura", "Molho shoyu+limão"],
    steps: "Asse o frango e sirva sobre a salada.",
  },
  {
    name: "Omelete de forno com batata-doce",
    category: "Café da manhã",
    servings: 2,
    prepMinutes: 35,
    kcal: 300,
    protein: 18,
    carbs: 28,
    fat: 12,
    ingredients: ["Ovos", "Batata-doce cozida", "Espinafre", "Queijo light"],
    steps: "Misture e asse em forma até firmar.",
  },
  {
    name: "Sopa de abóbora com carne seca light",
    category: "Jantar",
    servings: 3,
    prepMinutes: 45,
    kcal: 280,
    protein: 18,
    carbs: 30,
    fat: 8,
    ingredients: ["Abóbora", "Carne seca dessalgada (pouca)", "Cebola", "Leite desnatado opcional"],
    steps: "Cozinhe, bata a abóbora e acrescente a carne desfiada.",
  },
  {
    name: "Tacos de tilápia",
    category: "Almoço",
    servings: 2,
    prepMinutes: 25,
    kcal: 360,
    protein: 30,
    carbs: 32,
    fat: 10,
    ingredients: ["Tilápia", "Tortilha integral", "Repolho roxo", "Iogurte + limão"],
    steps: "Grelhe o peixe e monte os tacos.",
  },
  {
    name: "Energy balls de cacau e whey",
    category: "Lanche",
    servings: 8,
    prepMinutes: 15,
    kcal: 110,
    protein: 6,
    carbs: 10,
    fat: 5,
    ingredients: ["Aveia", "Whey", "Cacau", "Pasta de amendoim", "Mel ou tâmaras"],
    steps: "Misture, faça bolinhas e leve à geladeira.",
  },
  {
    name: "Frango ao molho mostarda e mel",
    category: "Almoço",
    servings: 2,
    prepMinutes: 30,
    kcal: 380,
    protein: 38,
    carbs: 16,
    fat: 14,
    ingredients: ["Frango", "Mostarda", "Mel (1 c.chá)", "Iogurte"],
    steps: "Grelhe o frango e finalize com o molho.",
  },
  {
    name: "Salada de abacate e grão-de-bico",
    category: "Lanche",
    servings: 1,
    prepMinutes: 10,
    kcal: 360,
    protein: 12,
    carbs: 28,
    fat: 22,
    ingredients: ["1/2 abacate", "Grão-de-bico", "Tomate", "Limão"],
    steps: "Misture com cuidado para não amassar demais o abacate.",
  },
  {
    name: "Ensopado de grão-de-bico com batata",
    category: "Jantar",
    servings: 3,
    prepMinutes: 40,
    kcal: 310,
    protein: 14,
    carbs: 48,
    fat: 6,
    ingredients: ["Grão-de-bico", "Batata", "Cenoura", "Páprica", "Alho"],
    steps: "Cozinhe tudo junto até engrossar.",
  },
  {
    name: "Café proteico gelado com aveia",
    category: "Café da manhã",
    servings: 1,
    prepMinutes: 5,
    kcal: 280,
    protein: 26,
    carbs: 28,
    fat: 5,
    ingredients: ["Café", "Whey", "20 g aveia", "Leite desnatado", "Gelo"],
    steps: "Bata tudo no liquidificador.",
  },
  {
    name: "Filé de peixe com crosta de castanha",
    category: "Jantar",
    servings: 1,
    prepMinutes: 25,
    kcal: 390,
    protein: 36,
    carbs: 8,
    fat: 22,
    ingredients: ["Peixe branco", "Castanha triturada", "Mostarda", "Limão"],
    steps: "Passe mostarda, cubra com castanha e asse.",
  },
  {
    name: "Bowl de arroz, feijão, ovo e salada (PF fitness)",
    category: "Almoço",
    servings: 1,
    prepMinutes: 20,
    kcal: 520,
    protein: 24,
    carbs: 65,
    fat: 14,
    ingredients: ["Arroz", "Feijão", "1 ovo", "Salada abundante", "Farofa mínima opcional"],
    steps: "Monte o prato feito equilibrado — base clássica brasileira.",
  },
];

export const RECIPE_SEED_COUNT = RECIPES.length;

/** Receitas prontas saudáveis (valores por porção aproximados). */
export function buildRecipeSeed(userId: number): Omit<Recipe, "id">[] {
  const now = new Date().toISOString();
  return RECIPES.map((r) => ({
    ...r,
    userId,
    createdAt: now,
    updatedAt: now,
    isSeed: true as const,
  }));
}
